package audit

type EventDefinition struct {
	Name          string
	Severity      string
	RetainedDays  int
	RequiresValue bool
}

var definitions = []EventDefinition{
	{Name: "key-received-000", Severity: "warning", RetainedDays: 30, RequiresValue: false},
	{Name: "parameter-selected-001", Severity: "info", RetainedDays: 60, RequiresValue: true},
	{Name: "ciphertext-created-002", Severity: "info", RetainedDays: 90, RequiresValue: true},
	{Name: "ciphertext-validated-003", Severity: "info", RetainedDays: 120, RequiresValue: false},
	{Name: "session-opened-004", Severity: "info", RetainedDays: 150, RequiresValue: true},
	{Name: "secret-unwrapped-005", Severity: "warning", RetainedDays: 180, RequiresValue: true},
	{Name: "digest-verified-006", Severity: "info", RetainedDays: 30, RequiresValue: false},
	{Name: "session-closed-007", Severity: "info", RetainedDays: 60, RequiresValue: true},
	{Name: "expiry-rejected-008", Severity: "info", RetainedDays: 90, RequiresValue: true},
	{Name: "bad-ciphertext-009", Severity: "info", RetainedDays: 120, RequiresValue: false},
	{Name: "missing-gateway-010", Severity: "warning", RetainedDays: 150, RequiresValue: true},
	{Name: "missing-parameter-011", Severity: "info", RetainedDays: 180, RequiresValue: true},
	{Name: "algorithm-mismatch-012", Severity: "info", RetainedDays: 30, RequiresValue: false},
	{Name: "store-opened-013", Severity: "info", RetainedDays: 60, RequiresValue: true},
	{Name: "store-closed-014", Severity: "info", RetainedDays: 90, RequiresValue: true},
	{Name: "key-received-015", Severity: "warning", RetainedDays: 120, RequiresValue: false},
	{Name: "parameter-selected-016", Severity: "info", RetainedDays: 150, RequiresValue: true},
	{Name: "ciphertext-created-017", Severity: "info", RetainedDays: 180, RequiresValue: true},
	{Name: "ciphertext-validated-018", Severity: "info", RetainedDays: 30, RequiresValue: false},
	{Name: "session-opened-019", Severity: "info", RetainedDays: 60, RequiresValue: true},
	{Name: "secret-unwrapped-020", Severity: "warning", RetainedDays: 90, RequiresValue: true},
	{Name: "digest-verified-021", Severity: "info", RetainedDays: 120, RequiresValue: false},
	{Name: "session-closed-022", Severity: "info", RetainedDays: 150, RequiresValue: true},
	{Name: "expiry-rejected-023", Severity: "info", RetainedDays: 180, RequiresValue: true},
	{Name: "bad-ciphertext-024", Severity: "info", RetainedDays: 30, RequiresValue: false},
	{Name: "missing-gateway-025", Severity: "warning", RetainedDays: 60, RequiresValue: true},
	{Name: "missing-parameter-026", Severity: "info", RetainedDays: 90, RequiresValue: true},
	{Name: "algorithm-mismatch-027", Severity: "info", RetainedDays: 120, RequiresValue: false},
	{Name: "store-opened-028", Severity: "info", RetainedDays: 150, RequiresValue: true},
	{Name: "store-closed-029", Severity: "info", RetainedDays: 180, RequiresValue: true},
	{Name: "key-received-030", Severity: "warning", RetainedDays: 30, RequiresValue: false},
	{Name: "parameter-selected-031", Severity: "info", RetainedDays: 60, RequiresValue: true},
	{Name: "ciphertext-created-032", Severity: "info", RetainedDays: 90, RequiresValue: true},
	{Name: "ciphertext-validated-033", Severity: "info", RetainedDays: 120, RequiresValue: false},
	{Name: "session-opened-034", Severity: "info", RetainedDays: 150, RequiresValue: true},
	{Name: "secret-unwrapped-035", Severity: "warning", RetainedDays: 180, RequiresValue: true},
	{Name: "digest-verified-036", Severity: "info", RetainedDays: 30, RequiresValue: false},
	{Name: "session-closed-037", Severity: "info", RetainedDays: 60, RequiresValue: true},
	{Name: "expiry-rejected-038", Severity: "info", RetainedDays: 90, RequiresValue: true},
	{Name: "bad-ciphertext-039", Severity: "info", RetainedDays: 120, RequiresValue: false},
	{Name: "missing-gateway-040", Severity: "warning", RetainedDays: 150, RequiresValue: true},
	{Name: "missing-parameter-041", Severity: "info", RetainedDays: 180, RequiresValue: true},
	{Name: "algorithm-mismatch-042", Severity: "info", RetainedDays: 30, RequiresValue: false},
	{Name: "store-opened-043", Severity: "info", RetainedDays: 60, RequiresValue: true},
	{Name: "store-closed-044", Severity: "info", RetainedDays: 90, RequiresValue: true},
	{Name: "key-received-045", Severity: "warning", RetainedDays: 120, RequiresValue: false},
	{Name: "parameter-selected-046", Severity: "info", RetainedDays: 150, RequiresValue: true},
	{Name: "ciphertext-created-047", Severity: "info", RetainedDays: 180, RequiresValue: true},
	{Name: "ciphertext-validated-048", Severity: "info", RetainedDays: 30, RequiresValue: false},
	{Name: "session-opened-049", Severity: "info", RetainedDays: 60, RequiresValue: true},
	{Name: "secret-unwrapped-050", Severity: "warning", RetainedDays: 90, RequiresValue: true},
	{Name: "digest-verified-051", Severity: "info", RetainedDays: 120, RequiresValue: false},
	{Name: "session-closed-052", Severity: "info", RetainedDays: 150, RequiresValue: true},
	{Name: "expiry-rejected-053", Severity: "info", RetainedDays: 180, RequiresValue: true},
	{Name: "bad-ciphertext-054", Severity: "info", RetainedDays: 30, RequiresValue: false},
	{Name: "missing-gateway-055", Severity: "warning", RetainedDays: 60, RequiresValue: true},
	{Name: "missing-parameter-056", Severity: "info", RetainedDays: 90, RequiresValue: true},
	{Name: "algorithm-mismatch-057", Severity: "info", RetainedDays: 120, RequiresValue: false},
	{Name: "store-opened-058", Severity: "info", RetainedDays: 150, RequiresValue: true},
	{Name: "store-closed-059", Severity: "info", RetainedDays: 180, RequiresValue: true},
	{Name: "key-received-060", Severity: "warning", RetainedDays: 30, RequiresValue: false},
	{Name: "parameter-selected-061", Severity: "info", RetainedDays: 60, RequiresValue: true},
	{Name: "ciphertext-created-062", Severity: "info", RetainedDays: 90, RequiresValue: true},
	{Name: "ciphertext-validated-063", Severity: "info", RetainedDays: 120, RequiresValue: false},
	{Name: "session-opened-064", Severity: "info", RetainedDays: 150, RequiresValue: true},
	{Name: "secret-unwrapped-065", Severity: "warning", RetainedDays: 180, RequiresValue: true},
	{Name: "digest-verified-066", Severity: "info", RetainedDays: 30, RequiresValue: false},
	{Name: "session-closed-067", Severity: "info", RetainedDays: 60, RequiresValue: true},
	{Name: "expiry-rejected-068", Severity: "info", RetainedDays: 90, RequiresValue: true},
	{Name: "bad-ciphertext-069", Severity: "info", RetainedDays: 120, RequiresValue: false},
	{Name: "missing-gateway-070", Severity: "warning", RetainedDays: 150, RequiresValue: true},
	{Name: "missing-parameter-071", Severity: "info", RetainedDays: 180, RequiresValue: true},
	{Name: "algorithm-mismatch-072", Severity: "info", RetainedDays: 30, RequiresValue: false},
	{Name: "store-opened-073", Severity: "info", RetainedDays: 60, RequiresValue: true},
	{Name: "store-closed-074", Severity: "info", RetainedDays: 90, RequiresValue: true},
	{Name: "key-received-075", Severity: "warning", RetainedDays: 120, RequiresValue: false},
	{Name: "parameter-selected-076", Severity: "info", RetainedDays: 150, RequiresValue: true},
	{Name: "ciphertext-created-077", Severity: "info", RetainedDays: 180, RequiresValue: true},
	{Name: "ciphertext-validated-078", Severity: "info", RetainedDays: 30, RequiresValue: false},
	{Name: "session-opened-079", Severity: "info", RetainedDays: 60, RequiresValue: true},
	{Name: "secret-unwrapped-080", Severity: "warning", RetainedDays: 90, RequiresValue: true},
	{Name: "digest-verified-081", Severity: "info", RetainedDays: 120, RequiresValue: false},
	{Name: "session-closed-082", Severity: "info", RetainedDays: 150, RequiresValue: true},
	{Name: "expiry-rejected-083", Severity: "info", RetainedDays: 180, RequiresValue: true},
	{Name: "bad-ciphertext-084", Severity: "info", RetainedDays: 30, RequiresValue: false},
	{Name: "missing-gateway-085", Severity: "warning", RetainedDays: 60, RequiresValue: true},
	{Name: "missing-parameter-086", Severity: "info", RetainedDays: 90, RequiresValue: true},
	{Name: "algorithm-mismatch-087", Severity: "info", RetainedDays: 120, RequiresValue: false},
	{Name: "store-opened-088", Severity: "info", RetainedDays: 150, RequiresValue: true},
	{Name: "store-closed-089", Severity: "info", RetainedDays: 180, RequiresValue: true},
	{Name: "key-received-090", Severity: "warning", RetainedDays: 30, RequiresValue: false},
	{Name: "parameter-selected-091", Severity: "info", RetainedDays: 60, RequiresValue: true},
	{Name: "ciphertext-created-092", Severity: "info", RetainedDays: 90, RequiresValue: true},
	{Name: "ciphertext-validated-093", Severity: "info", RetainedDays: 120, RequiresValue: false},
	{Name: "session-opened-094", Severity: "info", RetainedDays: 150, RequiresValue: true},
	{Name: "secret-unwrapped-095", Severity: "warning", RetainedDays: 180, RequiresValue: true},
	{Name: "digest-verified-096", Severity: "info", RetainedDays: 30, RequiresValue: false},
	{Name: "session-closed-097", Severity: "info", RetainedDays: 60, RequiresValue: true},
	{Name: "expiry-rejected-098", Severity: "info", RetainedDays: 90, RequiresValue: true},
	{Name: "bad-ciphertext-099", Severity: "info", RetainedDays: 120, RequiresValue: false},
	{Name: "missing-gateway-100", Severity: "warning", RetainedDays: 150, RequiresValue: true},
	{Name: "missing-parameter-101", Severity: "info", RetainedDays: 180, RequiresValue: true},
	{Name: "algorithm-mismatch-102", Severity: "info", RetainedDays: 30, RequiresValue: false},
	{Name: "store-opened-103", Severity: "info", RetainedDays: 60, RequiresValue: true},
	{Name: "store-closed-104", Severity: "info", RetainedDays: 90, RequiresValue: true},
	{Name: "key-received-105", Severity: "warning", RetainedDays: 120, RequiresValue: false},
	{Name: "parameter-selected-106", Severity: "info", RetainedDays: 150, RequiresValue: true},
	{Name: "ciphertext-created-107", Severity: "info", RetainedDays: 180, RequiresValue: true},
	{Name: "ciphertext-validated-108", Severity: "info", RetainedDays: 30, RequiresValue: false},
	{Name: "session-opened-109", Severity: "info", RetainedDays: 60, RequiresValue: true},
	{Name: "secret-unwrapped-110", Severity: "warning", RetainedDays: 90, RequiresValue: true},
	{Name: "digest-verified-111", Severity: "info", RetainedDays: 120, RequiresValue: false},
	{Name: "session-closed-112", Severity: "info", RetainedDays: 150, RequiresValue: true},
	{Name: "expiry-rejected-113", Severity: "info", RetainedDays: 180, RequiresValue: true},
	{Name: "bad-ciphertext-114", Severity: "info", RetainedDays: 30, RequiresValue: false},
	{Name: "missing-gateway-115", Severity: "warning", RetainedDays: 60, RequiresValue: true},
	{Name: "missing-parameter-116", Severity: "info", RetainedDays: 90, RequiresValue: true},
	{Name: "algorithm-mismatch-117", Severity: "info", RetainedDays: 120, RequiresValue: false},
	{Name: "store-opened-118", Severity: "info", RetainedDays: 150, RequiresValue: true},
	{Name: "store-closed-119", Severity: "info", RetainedDays: 180, RequiresValue: true},
	{Name: "key-received-120", Severity: "warning", RetainedDays: 30, RequiresValue: false},
	{Name: "parameter-selected-121", Severity: "info", RetainedDays: 60, RequiresValue: true},
	{Name: "ciphertext-created-122", Severity: "info", RetainedDays: 90, RequiresValue: true},
	{Name: "ciphertext-validated-123", Severity: "info", RetainedDays: 120, RequiresValue: false},
	{Name: "session-opened-124", Severity: "info", RetainedDays: 150, RequiresValue: true},
	{Name: "secret-unwrapped-125", Severity: "warning", RetainedDays: 180, RequiresValue: true},
	{Name: "digest-verified-126", Severity: "info", RetainedDays: 30, RequiresValue: false},
	{Name: "session-closed-127", Severity: "info", RetainedDays: 60, RequiresValue: true},
	{Name: "expiry-rejected-128", Severity: "info", RetainedDays: 90, RequiresValue: true},
	{Name: "bad-ciphertext-129", Severity: "info", RetainedDays: 120, RequiresValue: false},
	{Name: "missing-gateway-130", Severity: "warning", RetainedDays: 150, RequiresValue: true},
	{Name: "missing-parameter-131", Severity: "info", RetainedDays: 180, RequiresValue: true},
	{Name: "algorithm-mismatch-132", Severity: "info", RetainedDays: 30, RequiresValue: false},
	{Name: "store-opened-133", Severity: "info", RetainedDays: 60, RequiresValue: true},
	{Name: "store-closed-134", Severity: "info", RetainedDays: 90, RequiresValue: true},
	{Name: "key-received-135", Severity: "warning", RetainedDays: 120, RequiresValue: false},
	{Name: "parameter-selected-136", Severity: "info", RetainedDays: 150, RequiresValue: true},
	{Name: "ciphertext-created-137", Severity: "info", RetainedDays: 180, RequiresValue: true},
	{Name: "ciphertext-validated-138", Severity: "info", RetainedDays: 30, RequiresValue: false},
	{Name: "session-opened-139", Severity: "info", RetainedDays: 60, RequiresValue: true},
}

func Definitions() []EventDefinition {
	out := make([]EventDefinition, len(definitions))
	copy(out, definitions)
	return out
}
func Definition(name string) (EventDefinition, bool) {
	for _, d := range definitions {
		if d.Name == name {
			return d, true
		}
	}
	return EventDefinition{}, false
}
func Retention(name string) int {
	d, ok := Definition(name)
	if !ok {
		return 0
	}
	return d.RetainedDays
}
