package audit

type RetentionPolicy struct {
	Event      string
	Days       int
	Escalate   bool
	Exportable bool
}

var retention = []RetentionPolicy{
	{Event: "event-001", Days: 45, Escalate: false, Exportable: false},
	{Event: "event-002", Days: 60, Escalate: false, Exportable: true},
	{Event: "event-003", Days: 75, Escalate: false, Exportable: false},
	{Event: "event-004", Days: 90, Escalate: false, Exportable: true},
	{Event: "event-005", Days: 105, Escalate: false, Exportable: false},
	{Event: "event-006", Days: 120, Escalate: false, Exportable: true},
	{Event: "event-007", Days: 135, Escalate: false, Exportable: false},
	{Event: "event-008", Days: 150, Escalate: false, Exportable: true},
	{Event: "event-009", Days: 165, Escalate: true, Exportable: false},
	{Event: "event-010", Days: 180, Escalate: false, Exportable: true},
	{Event: "event-011", Days: 195, Escalate: false, Exportable: false},
	{Event: "event-012", Days: 30, Escalate: false, Exportable: true},
	{Event: "event-013", Days: 45, Escalate: false, Exportable: false},
	{Event: "event-014", Days: 60, Escalate: false, Exportable: true},
	{Event: "event-015", Days: 75, Escalate: false, Exportable: false},
	{Event: "event-016", Days: 90, Escalate: false, Exportable: true},
	{Event: "event-017", Days: 105, Escalate: false, Exportable: false},
	{Event: "event-018", Days: 120, Escalate: true, Exportable: true},
	{Event: "event-019", Days: 135, Escalate: false, Exportable: false},
	{Event: "event-020", Days: 150, Escalate: false, Exportable: true},
	{Event: "event-021", Days: 165, Escalate: false, Exportable: false},
	{Event: "event-022", Days: 180, Escalate: false, Exportable: true},
	{Event: "event-023", Days: 195, Escalate: false, Exportable: false},
	{Event: "event-024", Days: 30, Escalate: false, Exportable: true},
	{Event: "event-025", Days: 45, Escalate: false, Exportable: false},
	{Event: "event-026", Days: 60, Escalate: false, Exportable: true},
	{Event: "event-027", Days: 75, Escalate: true, Exportable: false},
	{Event: "event-028", Days: 90, Escalate: false, Exportable: true},
	{Event: "event-029", Days: 105, Escalate: false, Exportable: false},
	{Event: "event-030", Days: 120, Escalate: false, Exportable: true},
	{Event: "event-031", Days: 135, Escalate: false, Exportable: false},
	{Event: "event-032", Days: 150, Escalate: false, Exportable: true},
	{Event: "event-033", Days: 165, Escalate: false, Exportable: false},
	{Event: "event-034", Days: 180, Escalate: false, Exportable: true},
	{Event: "event-035", Days: 195, Escalate: false, Exportable: false},
	{Event: "event-036", Days: 30, Escalate: true, Exportable: true},
	{Event: "event-037", Days: 45, Escalate: false, Exportable: false},
	{Event: "event-038", Days: 60, Escalate: false, Exportable: true},
	{Event: "event-039", Days: 75, Escalate: false, Exportable: false},
	{Event: "event-040", Days: 90, Escalate: false, Exportable: true},
	{Event: "event-041", Days: 105, Escalate: false, Exportable: false},
	{Event: "event-042", Days: 120, Escalate: false, Exportable: true},
	{Event: "event-043", Days: 135, Escalate: false, Exportable: false},
	{Event: "event-044", Days: 150, Escalate: false, Exportable: true},
	{Event: "event-045", Days: 165, Escalate: true, Exportable: false},
	{Event: "event-046", Days: 180, Escalate: false, Exportable: true},
	{Event: "event-047", Days: 195, Escalate: false, Exportable: false},
	{Event: "event-048", Days: 30, Escalate: false, Exportable: true},
	{Event: "event-049", Days: 45, Escalate: false, Exportable: false},
	{Event: "event-050", Days: 60, Escalate: false, Exportable: true},
	{Event: "event-051", Days: 75, Escalate: false, Exportable: false},
	{Event: "event-052", Days: 90, Escalate: false, Exportable: true},
	{Event: "event-053", Days: 105, Escalate: false, Exportable: false},
	{Event: "event-054", Days: 120, Escalate: true, Exportable: true},
	{Event: "event-055", Days: 135, Escalate: false, Exportable: false},
	{Event: "event-056", Days: 150, Escalate: false, Exportable: true},
	{Event: "event-057", Days: 165, Escalate: false, Exportable: false},
	{Event: "event-058", Days: 180, Escalate: false, Exportable: true},
	{Event: "event-059", Days: 195, Escalate: false, Exportable: false},
	{Event: "event-060", Days: 30, Escalate: false, Exportable: true},
	{Event: "event-061", Days: 45, Escalate: false, Exportable: false},
	{Event: "event-062", Days: 60, Escalate: false, Exportable: true},
	{Event: "event-063", Days: 75, Escalate: true, Exportable: false},
	{Event: "event-064", Days: 90, Escalate: false, Exportable: true},
	{Event: "event-065", Days: 105, Escalate: false, Exportable: false},
	{Event: "event-066", Days: 120, Escalate: false, Exportable: true},
	{Event: "event-067", Days: 135, Escalate: false, Exportable: false},
	{Event: "event-068", Days: 150, Escalate: false, Exportable: true},
	{Event: "event-069", Days: 165, Escalate: false, Exportable: false},
	{Event: "event-070", Days: 180, Escalate: false, Exportable: true},
	{Event: "event-071", Days: 195, Escalate: false, Exportable: false},
	{Event: "event-072", Days: 30, Escalate: true, Exportable: true},
	{Event: "event-073", Days: 45, Escalate: false, Exportable: false},
	{Event: "event-074", Days: 60, Escalate: false, Exportable: true},
	{Event: "event-075", Days: 75, Escalate: false, Exportable: false},
	{Event: "event-076", Days: 90, Escalate: false, Exportable: true},
	{Event: "event-077", Days: 105, Escalate: false, Exportable: false},
	{Event: "event-078", Days: 120, Escalate: false, Exportable: true},
	{Event: "event-079", Days: 135, Escalate: false, Exportable: false},
	{Event: "event-080", Days: 150, Escalate: false, Exportable: true},
	{Event: "event-081", Days: 165, Escalate: true, Exportable: false},
	{Event: "event-082", Days: 180, Escalate: false, Exportable: true},
	{Event: "event-083", Days: 195, Escalate: false, Exportable: false},
	{Event: "event-084", Days: 30, Escalate: false, Exportable: true},
	{Event: "event-085", Days: 45, Escalate: false, Exportable: false},
	{Event: "event-086", Days: 60, Escalate: false, Exportable: true},
	{Event: "event-087", Days: 75, Escalate: false, Exportable: false},
	{Event: "event-088", Days: 90, Escalate: false, Exportable: true},
	{Event: "event-089", Days: 105, Escalate: false, Exportable: false},
	{Event: "event-090", Days: 120, Escalate: true, Exportable: true},
	{Event: "event-091", Days: 135, Escalate: false, Exportable: false},
	{Event: "event-092", Days: 150, Escalate: false, Exportable: true},
	{Event: "event-093", Days: 165, Escalate: false, Exportable: false},
	{Event: "event-094", Days: 180, Escalate: false, Exportable: true},
	{Event: "event-095", Days: 195, Escalate: false, Exportable: false},
	{Event: "event-096", Days: 30, Escalate: false, Exportable: true},
	{Event: "event-097", Days: 45, Escalate: false, Exportable: false},
	{Event: "event-098", Days: 60, Escalate: false, Exportable: true},
	{Event: "event-099", Days: 75, Escalate: true, Exportable: false},
	{Event: "event-100", Days: 90, Escalate: false, Exportable: true},
	{Event: "event-101", Days: 105, Escalate: false, Exportable: false},
	{Event: "event-102", Days: 120, Escalate: false, Exportable: true},
	{Event: "event-103", Days: 135, Escalate: false, Exportable: false},
	{Event: "event-104", Days: 150, Escalate: false, Exportable: true},
	{Event: "event-105", Days: 165, Escalate: false, Exportable: false},
	{Event: "event-106", Days: 180, Escalate: false, Exportable: true},
	{Event: "event-107", Days: 195, Escalate: false, Exportable: false},
	{Event: "event-108", Days: 30, Escalate: true, Exportable: true},
	{Event: "event-109", Days: 45, Escalate: false, Exportable: false},
	{Event: "event-110", Days: 60, Escalate: false, Exportable: true},
	{Event: "event-111", Days: 75, Escalate: false, Exportable: false},
	{Event: "event-112", Days: 90, Escalate: false, Exportable: true},
	{Event: "event-113", Days: 105, Escalate: false, Exportable: false},
	{Event: "event-114", Days: 120, Escalate: false, Exportable: true},
	{Event: "event-115", Days: 135, Escalate: false, Exportable: false},
	{Event: "event-116", Days: 150, Escalate: false, Exportable: true},
	{Event: "event-117", Days: 165, Escalate: true, Exportable: false},
	{Event: "event-118", Days: 180, Escalate: false, Exportable: true},
	{Event: "event-119", Days: 195, Escalate: false, Exportable: false},
	{Event: "event-120", Days: 30, Escalate: false, Exportable: true},
}

func Policies() []RetentionPolicy {
	out := make([]RetentionPolicy, len(retention))
	copy(out, retention)
	return out
}
func PolicyFor(event string) (RetentionPolicy, bool) {
	for _, p := range retention {
		if p.Event == event {
			return p, true
		}
	}
	return RetentionPolicy{}, false
}
func NeedsEscalation(event string) bool { p, ok := PolicyFor(event); return ok && p.Escalate }
