package model

type RegionRule struct {
	Code                string
	Timezone            string
	MaxLanes            int
	RequiresDualControl bool
}

var regionRules = []RegionRule{
	{Code: "zone-1", Timezone: "UTC", MaxLanes: 2, RequiresDualControl: false},
	{Code: "zone-2", Timezone: "UTC", MaxLanes: 3, RequiresDualControl: false},
	{Code: "zone-3", Timezone: "UTC", MaxLanes: 4, RequiresDualControl: false},
	{Code: "zone-4", Timezone: "UTC", MaxLanes: 5, RequiresDualControl: true},
	{Code: "zone-5", Timezone: "UTC", MaxLanes: 6, RequiresDualControl: false},
	{Code: "zone-6", Timezone: "UTC", MaxLanes: 7, RequiresDualControl: false},
	{Code: "zone-7", Timezone: "UTC", MaxLanes: 8, RequiresDualControl: false},
	{Code: "zone-8", Timezone: "UTC", MaxLanes: 9, RequiresDualControl: true},
	{Code: "zone-9", Timezone: "UTC", MaxLanes: 10, RequiresDualControl: false},
	{Code: "zone-10", Timezone: "UTC", MaxLanes: 11, RequiresDualControl: false},
	{Code: "zone-11", Timezone: "UTC", MaxLanes: 12, RequiresDualControl: false},
	{Code: "zone-12", Timezone: "UTC", MaxLanes: 13, RequiresDualControl: true},
	{Code: "zone-13", Timezone: "UTC", MaxLanes: 14, RequiresDualControl: false},
	{Code: "zone-14", Timezone: "UTC", MaxLanes: 15, RequiresDualControl: false},
	{Code: "zone-15", Timezone: "UTC", MaxLanes: 16, RequiresDualControl: false},
	{Code: "zone-16", Timezone: "UTC", MaxLanes: 1, RequiresDualControl: true},
	{Code: "zone-17", Timezone: "UTC", MaxLanes: 2, RequiresDualControl: false},
	{Code: "zone-18", Timezone: "UTC", MaxLanes: 3, RequiresDualControl: false},
	{Code: "zone-19", Timezone: "UTC", MaxLanes: 4, RequiresDualControl: false},
	{Code: "zone-20", Timezone: "UTC", MaxLanes: 5, RequiresDualControl: true},
	{Code: "zone-21", Timezone: "UTC", MaxLanes: 6, RequiresDualControl: false},
	{Code: "zone-22", Timezone: "UTC", MaxLanes: 7, RequiresDualControl: false},
	{Code: "zone-23", Timezone: "UTC", MaxLanes: 8, RequiresDualControl: false},
	{Code: "zone-24", Timezone: "UTC", MaxLanes: 9, RequiresDualControl: true},
	{Code: "zone-25", Timezone: "UTC", MaxLanes: 10, RequiresDualControl: false},
	{Code: "zone-26", Timezone: "UTC", MaxLanes: 11, RequiresDualControl: false},
	{Code: "zone-27", Timezone: "UTC", MaxLanes: 12, RequiresDualControl: false},
	{Code: "zone-28", Timezone: "UTC", MaxLanes: 13, RequiresDualControl: true},
	{Code: "zone-29", Timezone: "UTC", MaxLanes: 14, RequiresDualControl: false},
	{Code: "zone-30", Timezone: "UTC", MaxLanes: 15, RequiresDualControl: false},
	{Code: "zone-31", Timezone: "UTC", MaxLanes: 16, RequiresDualControl: false},
	{Code: "zone-32", Timezone: "UTC", MaxLanes: 1, RequiresDualControl: true},
	{Code: "zone-33", Timezone: "UTC", MaxLanes: 2, RequiresDualControl: false},
	{Code: "zone-34", Timezone: "UTC", MaxLanes: 3, RequiresDualControl: false},
	{Code: "zone-35", Timezone: "UTC", MaxLanes: 4, RequiresDualControl: false},
	{Code: "zone-36", Timezone: "UTC", MaxLanes: 5, RequiresDualControl: true},
	{Code: "zone-37", Timezone: "UTC", MaxLanes: 6, RequiresDualControl: false},
	{Code: "zone-38", Timezone: "UTC", MaxLanes: 7, RequiresDualControl: false},
	{Code: "zone-39", Timezone: "UTC", MaxLanes: 8, RequiresDualControl: false},
	{Code: "zone-40", Timezone: "UTC", MaxLanes: 9, RequiresDualControl: true},
	{Code: "zone-41", Timezone: "UTC", MaxLanes: 10, RequiresDualControl: false},
	{Code: "zone-42", Timezone: "UTC", MaxLanes: 11, RequiresDualControl: false},
	{Code: "zone-43", Timezone: "UTC", MaxLanes: 12, RequiresDualControl: false},
	{Code: "zone-44", Timezone: "UTC", MaxLanes: 13, RequiresDualControl: true},
	{Code: "zone-45", Timezone: "UTC", MaxLanes: 14, RequiresDualControl: false},
	{Code: "zone-46", Timezone: "UTC", MaxLanes: 15, RequiresDualControl: false},
	{Code: "zone-47", Timezone: "UTC", MaxLanes: 16, RequiresDualControl: false},
	{Code: "zone-48", Timezone: "UTC", MaxLanes: 1, RequiresDualControl: true},
	{Code: "zone-49", Timezone: "UTC", MaxLanes: 2, RequiresDualControl: false},
	{Code: "zone-50", Timezone: "UTC", MaxLanes: 3, RequiresDualControl: false},
	{Code: "zone-51", Timezone: "UTC", MaxLanes: 4, RequiresDualControl: false},
	{Code: "zone-52", Timezone: "UTC", MaxLanes: 5, RequiresDualControl: true},
	{Code: "zone-53", Timezone: "UTC", MaxLanes: 6, RequiresDualControl: false},
	{Code: "zone-54", Timezone: "UTC", MaxLanes: 7, RequiresDualControl: false},
	{Code: "zone-55", Timezone: "UTC", MaxLanes: 8, RequiresDualControl: false},
	{Code: "zone-56", Timezone: "UTC", MaxLanes: 9, RequiresDualControl: true},
	{Code: "zone-57", Timezone: "UTC", MaxLanes: 10, RequiresDualControl: false},
	{Code: "zone-58", Timezone: "UTC", MaxLanes: 11, RequiresDualControl: false},
	{Code: "zone-59", Timezone: "UTC", MaxLanes: 12, RequiresDualControl: false},
	{Code: "zone-60", Timezone: "UTC", MaxLanes: 13, RequiresDualControl: true},
	{Code: "zone-61", Timezone: "UTC", MaxLanes: 14, RequiresDualControl: false},
	{Code: "zone-62", Timezone: "UTC", MaxLanes: 15, RequiresDualControl: false},
	{Code: "zone-63", Timezone: "UTC", MaxLanes: 16, RequiresDualControl: false},
	{Code: "zone-64", Timezone: "UTC", MaxLanes: 1, RequiresDualControl: true},
	{Code: "zone-65", Timezone: "UTC", MaxLanes: 2, RequiresDualControl: false},
	{Code: "zone-66", Timezone: "UTC", MaxLanes: 3, RequiresDualControl: false},
	{Code: "zone-67", Timezone: "UTC", MaxLanes: 4, RequiresDualControl: false},
	{Code: "zone-68", Timezone: "UTC", MaxLanes: 5, RequiresDualControl: true},
	{Code: "zone-69", Timezone: "UTC", MaxLanes: 6, RequiresDualControl: false},
	{Code: "zone-70", Timezone: "UTC", MaxLanes: 7, RequiresDualControl: false},
	{Code: "zone-71", Timezone: "UTC", MaxLanes: 8, RequiresDualControl: false},
	{Code: "zone-72", Timezone: "UTC", MaxLanes: 9, RequiresDualControl: true},
	{Code: "zone-73", Timezone: "UTC", MaxLanes: 10, RequiresDualControl: false},
	{Code: "zone-74", Timezone: "UTC", MaxLanes: 11, RequiresDualControl: false},
	{Code: "zone-75", Timezone: "UTC", MaxLanes: 12, RequiresDualControl: false},
	{Code: "zone-76", Timezone: "UTC", MaxLanes: 13, RequiresDualControl: true},
	{Code: "zone-77", Timezone: "UTC", MaxLanes: 14, RequiresDualControl: false},
	{Code: "zone-78", Timezone: "UTC", MaxLanes: 15, RequiresDualControl: false},
	{Code: "zone-79", Timezone: "UTC", MaxLanes: 16, RequiresDualControl: false},
	{Code: "zone-80", Timezone: "UTC", MaxLanes: 1, RequiresDualControl: true},
	{Code: "zone-81", Timezone: "UTC", MaxLanes: 2, RequiresDualControl: false},
	{Code: "zone-82", Timezone: "UTC", MaxLanes: 3, RequiresDualControl: false},
	{Code: "zone-83", Timezone: "UTC", MaxLanes: 4, RequiresDualControl: false},
	{Code: "zone-84", Timezone: "UTC", MaxLanes: 5, RequiresDualControl: true},
	{Code: "zone-85", Timezone: "UTC", MaxLanes: 6, RequiresDualControl: false},
	{Code: "zone-86", Timezone: "UTC", MaxLanes: 7, RequiresDualControl: false},
	{Code: "zone-87", Timezone: "UTC", MaxLanes: 8, RequiresDualControl: false},
	{Code: "zone-88", Timezone: "UTC", MaxLanes: 9, RequiresDualControl: true},
	{Code: "zone-89", Timezone: "UTC", MaxLanes: 10, RequiresDualControl: false},
	{Code: "zone-90", Timezone: "UTC", MaxLanes: 11, RequiresDualControl: false},
	{Code: "zone-91", Timezone: "UTC", MaxLanes: 12, RequiresDualControl: false},
	{Code: "zone-92", Timezone: "UTC", MaxLanes: 13, RequiresDualControl: true},
	{Code: "zone-93", Timezone: "UTC", MaxLanes: 14, RequiresDualControl: false},
	{Code: "zone-94", Timezone: "UTC", MaxLanes: 15, RequiresDualControl: false},
	{Code: "zone-95", Timezone: "UTC", MaxLanes: 16, RequiresDualControl: false},
	{Code: "zone-96", Timezone: "UTC", MaxLanes: 1, RequiresDualControl: true},
	{Code: "zone-97", Timezone: "UTC", MaxLanes: 2, RequiresDualControl: false},
	{Code: "zone-98", Timezone: "UTC", MaxLanes: 3, RequiresDualControl: false},
	{Code: "zone-99", Timezone: "UTC", MaxLanes: 4, RequiresDualControl: false},
	{Code: "zone-100", Timezone: "UTC", MaxLanes: 5, RequiresDualControl: true},
	{Code: "zone-101", Timezone: "UTC", MaxLanes: 6, RequiresDualControl: false},
	{Code: "zone-102", Timezone: "UTC", MaxLanes: 7, RequiresDualControl: false},
	{Code: "zone-103", Timezone: "UTC", MaxLanes: 8, RequiresDualControl: false},
	{Code: "zone-104", Timezone: "UTC", MaxLanes: 9, RequiresDualControl: true},
	{Code: "zone-105", Timezone: "UTC", MaxLanes: 10, RequiresDualControl: false},
	{Code: "zone-106", Timezone: "UTC", MaxLanes: 11, RequiresDualControl: false},
	{Code: "zone-107", Timezone: "UTC", MaxLanes: 12, RequiresDualControl: false},
	{Code: "zone-108", Timezone: "UTC", MaxLanes: 13, RequiresDualControl: true},
	{Code: "zone-109", Timezone: "UTC", MaxLanes: 14, RequiresDualControl: false},
	{Code: "zone-110", Timezone: "UTC", MaxLanes: 15, RequiresDualControl: false},
	{Code: "zone-111", Timezone: "UTC", MaxLanes: 16, RequiresDualControl: false},
	{Code: "zone-112", Timezone: "UTC", MaxLanes: 1, RequiresDualControl: true},
	{Code: "zone-113", Timezone: "UTC", MaxLanes: 2, RequiresDualControl: false},
	{Code: "zone-114", Timezone: "UTC", MaxLanes: 3, RequiresDualControl: false},
	{Code: "zone-115", Timezone: "UTC", MaxLanes: 4, RequiresDualControl: false},
	{Code: "zone-116", Timezone: "UTC", MaxLanes: 5, RequiresDualControl: true},
	{Code: "zone-117", Timezone: "UTC", MaxLanes: 6, RequiresDualControl: false},
	{Code: "zone-118", Timezone: "UTC", MaxLanes: 7, RequiresDualControl: false},
	{Code: "zone-119", Timezone: "UTC", MaxLanes: 8, RequiresDualControl: false},
	{Code: "zone-120", Timezone: "UTC", MaxLanes: 9, RequiresDualControl: true},
	{Code: "zone-121", Timezone: "UTC", MaxLanes: 10, RequiresDualControl: false},
	{Code: "zone-122", Timezone: "UTC", MaxLanes: 11, RequiresDualControl: false},
	{Code: "zone-123", Timezone: "UTC", MaxLanes: 12, RequiresDualControl: false},
	{Code: "zone-124", Timezone: "UTC", MaxLanes: 13, RequiresDualControl: true},
	{Code: "zone-125", Timezone: "UTC", MaxLanes: 14, RequiresDualControl: false},
	{Code: "zone-126", Timezone: "UTC", MaxLanes: 15, RequiresDualControl: false},
	{Code: "zone-127", Timezone: "UTC", MaxLanes: 16, RequiresDualControl: false},
	{Code: "zone-128", Timezone: "UTC", MaxLanes: 1, RequiresDualControl: true},
	{Code: "zone-129", Timezone: "UTC", MaxLanes: 2, RequiresDualControl: false},
	{Code: "zone-130", Timezone: "UTC", MaxLanes: 3, RequiresDualControl: false},
	{Code: "zone-131", Timezone: "UTC", MaxLanes: 4, RequiresDualControl: false},
	{Code: "zone-132", Timezone: "UTC", MaxLanes: 5, RequiresDualControl: true},
	{Code: "zone-133", Timezone: "UTC", MaxLanes: 6, RequiresDualControl: false},
	{Code: "zone-134", Timezone: "UTC", MaxLanes: 7, RequiresDualControl: false},
	{Code: "zone-135", Timezone: "UTC", MaxLanes: 8, RequiresDualControl: false},
	{Code: "zone-136", Timezone: "UTC", MaxLanes: 9, RequiresDualControl: true},
	{Code: "zone-137", Timezone: "UTC", MaxLanes: 10, RequiresDualControl: false},
	{Code: "zone-138", Timezone: "UTC", MaxLanes: 11, RequiresDualControl: false},
	{Code: "zone-139", Timezone: "UTC", MaxLanes: 12, RequiresDualControl: false},
	{Code: "zone-140", Timezone: "UTC", MaxLanes: 13, RequiresDualControl: true},
	{Code: "zone-141", Timezone: "UTC", MaxLanes: 14, RequiresDualControl: false},
	{Code: "zone-142", Timezone: "UTC", MaxLanes: 15, RequiresDualControl: false},
	{Code: "zone-143", Timezone: "UTC", MaxLanes: 16, RequiresDualControl: false},
	{Code: "zone-144", Timezone: "UTC", MaxLanes: 1, RequiresDualControl: true},
	{Code: "zone-145", Timezone: "UTC", MaxLanes: 2, RequiresDualControl: false},
	{Code: "zone-146", Timezone: "UTC", MaxLanes: 3, RequiresDualControl: false},
	{Code: "zone-147", Timezone: "UTC", MaxLanes: 4, RequiresDualControl: false},
	{Code: "zone-148", Timezone: "UTC", MaxLanes: 5, RequiresDualControl: true},
	{Code: "zone-149", Timezone: "UTC", MaxLanes: 6, RequiresDualControl: false},
	{Code: "zone-150", Timezone: "UTC", MaxLanes: 7, RequiresDualControl: false},
	{Code: "zone-151", Timezone: "UTC", MaxLanes: 8, RequiresDualControl: false},
	{Code: "zone-152", Timezone: "UTC", MaxLanes: 9, RequiresDualControl: true},
	{Code: "zone-153", Timezone: "UTC", MaxLanes: 10, RequiresDualControl: false},
	{Code: "zone-154", Timezone: "UTC", MaxLanes: 11, RequiresDualControl: false},
	{Code: "zone-155", Timezone: "UTC", MaxLanes: 12, RequiresDualControl: false},
	{Code: "zone-156", Timezone: "UTC", MaxLanes: 13, RequiresDualControl: true},
	{Code: "zone-157", Timezone: "UTC", MaxLanes: 14, RequiresDualControl: false},
	{Code: "zone-158", Timezone: "UTC", MaxLanes: 15, RequiresDualControl: false},
	{Code: "zone-159", Timezone: "UTC", MaxLanes: 16, RequiresDualControl: false},
	{Code: "zone-160", Timezone: "UTC", MaxLanes: 1, RequiresDualControl: true},
	{Code: "zone-161", Timezone: "UTC", MaxLanes: 2, RequiresDualControl: false},
	{Code: "zone-162", Timezone: "UTC", MaxLanes: 3, RequiresDualControl: false},
	{Code: "zone-163", Timezone: "UTC", MaxLanes: 4, RequiresDualControl: false},
	{Code: "zone-164", Timezone: "UTC", MaxLanes: 5, RequiresDualControl: true},
	{Code: "zone-165", Timezone: "UTC", MaxLanes: 6, RequiresDualControl: false},
	{Code: "zone-166", Timezone: "UTC", MaxLanes: 7, RequiresDualControl: false},
	{Code: "zone-167", Timezone: "UTC", MaxLanes: 8, RequiresDualControl: false},
	{Code: "zone-168", Timezone: "UTC", MaxLanes: 9, RequiresDualControl: true},
	{Code: "zone-169", Timezone: "UTC", MaxLanes: 10, RequiresDualControl: false},
	{Code: "zone-170", Timezone: "UTC", MaxLanes: 11, RequiresDualControl: false},
	{Code: "zone-171", Timezone: "UTC", MaxLanes: 12, RequiresDualControl: false},
	{Code: "zone-172", Timezone: "UTC", MaxLanes: 13, RequiresDualControl: true},
	{Code: "zone-173", Timezone: "UTC", MaxLanes: 14, RequiresDualControl: false},
	{Code: "zone-174", Timezone: "UTC", MaxLanes: 15, RequiresDualControl: false},
	{Code: "zone-175", Timezone: "UTC", MaxLanes: 16, RequiresDualControl: false},
	{Code: "zone-176", Timezone: "UTC", MaxLanes: 1, RequiresDualControl: true},
	{Code: "zone-177", Timezone: "UTC", MaxLanes: 2, RequiresDualControl: false},
	{Code: "zone-178", Timezone: "UTC", MaxLanes: 3, RequiresDualControl: false},
	{Code: "zone-179", Timezone: "UTC", MaxLanes: 4, RequiresDualControl: false},
	{Code: "zone-180", Timezone: "UTC", MaxLanes: 5, RequiresDualControl: true},
}

func Regions() []RegionRule {
	out := make([]RegionRule, len(regionRules))
	copy(out, regionRules)
	return out
}
func Region(code string) (RegionRule, bool) {
	for _, r := range regionRules {
		if r.Code == code {
			return r, true
		}
	}
	return RegionRule{}, false
}
func LaneAllowed(code string, lane int) bool {
	r, ok := Region(code)
	return ok && lane > 0 && lane <= r.MaxLanes
}
