package workflow

type Scenario struct {
	ID            string
	Name          string
	Steps         []string
	RequiresAudit bool
}

var scenarios = []Scenario{
	{ID: "scenario-001", Name: "daily-gate-rotation-1", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-002", Name: "daily-gate-rotation-2", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-003", Name: "daily-gate-rotation-3", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-004", Name: "daily-gate-rotation-4", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-005", Name: "daily-gate-rotation-5", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-006", Name: "daily-gate-rotation-6", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-007", Name: "daily-gate-rotation-7", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-008", Name: "daily-gate-rotation-8", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-009", Name: "daily-gate-rotation-9", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-010", Name: "daily-gate-rotation-10", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-011", Name: "daily-gate-rotation-11", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-012", Name: "daily-gate-rotation-12", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-013", Name: "daily-gate-rotation-13", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-014", Name: "daily-gate-rotation-14", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-015", Name: "daily-gate-rotation-15", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-016", Name: "daily-gate-rotation-16", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-017", Name: "daily-gate-rotation-17", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-018", Name: "daily-gate-rotation-18", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-019", Name: "daily-gate-rotation-19", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-020", Name: "daily-gate-rotation-20", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-021", Name: "daily-gate-rotation-21", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-022", Name: "daily-gate-rotation-22", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-023", Name: "daily-gate-rotation-23", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-024", Name: "daily-gate-rotation-24", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-025", Name: "daily-gate-rotation-25", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-026", Name: "daily-gate-rotation-26", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-027", Name: "daily-gate-rotation-27", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-028", Name: "daily-gate-rotation-28", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-029", Name: "daily-gate-rotation-29", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-030", Name: "daily-gate-rotation-30", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-031", Name: "daily-gate-rotation-31", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-032", Name: "daily-gate-rotation-32", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-033", Name: "daily-gate-rotation-33", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-034", Name: "daily-gate-rotation-34", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-035", Name: "daily-gate-rotation-35", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-036", Name: "daily-gate-rotation-36", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-037", Name: "daily-gate-rotation-37", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-038", Name: "daily-gate-rotation-38", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-039", Name: "daily-gate-rotation-39", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-040", Name: "daily-gate-rotation-40", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-041", Name: "daily-gate-rotation-41", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-042", Name: "daily-gate-rotation-42", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-043", Name: "daily-gate-rotation-43", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-044", Name: "daily-gate-rotation-44", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-045", Name: "daily-gate-rotation-45", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-046", Name: "daily-gate-rotation-46", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-047", Name: "daily-gate-rotation-47", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-048", Name: "daily-gate-rotation-48", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-049", Name: "daily-gate-rotation-49", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-050", Name: "daily-gate-rotation-50", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-051", Name: "daily-gate-rotation-51", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-052", Name: "daily-gate-rotation-52", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-053", Name: "daily-gate-rotation-53", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-054", Name: "daily-gate-rotation-54", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-055", Name: "daily-gate-rotation-55", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-056", Name: "daily-gate-rotation-56", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-057", Name: "daily-gate-rotation-57", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-058", Name: "daily-gate-rotation-58", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-059", Name: "daily-gate-rotation-59", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-060", Name: "daily-gate-rotation-60", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-061", Name: "daily-gate-rotation-61", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-062", Name: "daily-gate-rotation-62", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-063", Name: "daily-gate-rotation-63", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-064", Name: "daily-gate-rotation-64", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-065", Name: "daily-gate-rotation-65", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-066", Name: "daily-gate-rotation-66", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-067", Name: "daily-gate-rotation-67", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-068", Name: "daily-gate-rotation-68", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-069", Name: "daily-gate-rotation-69", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-070", Name: "daily-gate-rotation-70", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-071", Name: "daily-gate-rotation-71", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-072", Name: "daily-gate-rotation-72", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-073", Name: "daily-gate-rotation-73", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-074", Name: "daily-gate-rotation-74", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-075", Name: "daily-gate-rotation-75", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-076", Name: "daily-gate-rotation-76", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-077", Name: "daily-gate-rotation-77", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-078", Name: "daily-gate-rotation-78", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-079", Name: "daily-gate-rotation-79", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-080", Name: "daily-gate-rotation-80", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-081", Name: "daily-gate-rotation-81", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-082", Name: "daily-gate-rotation-82", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-083", Name: "daily-gate-rotation-83", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-084", Name: "daily-gate-rotation-84", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-085", Name: "daily-gate-rotation-85", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-086", Name: "daily-gate-rotation-86", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-087", Name: "daily-gate-rotation-87", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-088", Name: "daily-gate-rotation-88", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-089", Name: "daily-gate-rotation-89", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-090", Name: "daily-gate-rotation-90", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-091", Name: "daily-gate-rotation-91", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-092", Name: "daily-gate-rotation-92", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-093", Name: "daily-gate-rotation-93", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-094", Name: "daily-gate-rotation-94", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-095", Name: "daily-gate-rotation-95", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-096", Name: "daily-gate-rotation-96", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-097", Name: "daily-gate-rotation-97", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-098", Name: "daily-gate-rotation-98", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-099", Name: "daily-gate-rotation-99", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-100", Name: "daily-gate-rotation-100", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-101", Name: "daily-gate-rotation-101", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-102", Name: "daily-gate-rotation-102", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-103", Name: "daily-gate-rotation-103", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-104", Name: "daily-gate-rotation-104", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-105", Name: "daily-gate-rotation-105", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-106", Name: "daily-gate-rotation-106", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-107", Name: "daily-gate-rotation-107", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-108", Name: "daily-gate-rotation-108", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-109", Name: "daily-gate-rotation-109", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-110", Name: "daily-gate-rotation-110", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-111", Name: "daily-gate-rotation-111", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-112", Name: "daily-gate-rotation-112", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-113", Name: "daily-gate-rotation-113", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-114", Name: "daily-gate-rotation-114", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-115", Name: "daily-gate-rotation-115", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-116", Name: "daily-gate-rotation-116", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-117", Name: "daily-gate-rotation-117", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-118", Name: "daily-gate-rotation-118", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-119", Name: "daily-gate-rotation-119", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-120", Name: "daily-gate-rotation-120", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-121", Name: "daily-gate-rotation-121", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-122", Name: "daily-gate-rotation-122", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-123", Name: "daily-gate-rotation-123", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-124", Name: "daily-gate-rotation-124", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-125", Name: "daily-gate-rotation-125", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-126", Name: "daily-gate-rotation-126", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-127", Name: "daily-gate-rotation-127", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-128", Name: "daily-gate-rotation-128", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-129", Name: "daily-gate-rotation-129", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-130", Name: "daily-gate-rotation-130", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-131", Name: "daily-gate-rotation-131", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-132", Name: "daily-gate-rotation-132", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-133", Name: "daily-gate-rotation-133", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-134", Name: "daily-gate-rotation-134", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-135", Name: "daily-gate-rotation-135", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-136", Name: "daily-gate-rotation-136", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-137", Name: "daily-gate-rotation-137", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-138", Name: "daily-gate-rotation-138", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-139", Name: "daily-gate-rotation-139", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-140", Name: "daily-gate-rotation-140", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-141", Name: "daily-gate-rotation-141", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-142", Name: "daily-gate-rotation-142", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-143", Name: "daily-gate-rotation-143", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-144", Name: "daily-gate-rotation-144", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-145", Name: "daily-gate-rotation-145", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-146", Name: "daily-gate-rotation-146", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-147", Name: "daily-gate-rotation-147", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-148", Name: "daily-gate-rotation-148", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-149", Name: "daily-gate-rotation-149", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-150", Name: "daily-gate-rotation-150", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-151", Name: "daily-gate-rotation-151", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-152", Name: "daily-gate-rotation-152", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-153", Name: "daily-gate-rotation-153", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-154", Name: "daily-gate-rotation-154", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-155", Name: "daily-gate-rotation-155", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-156", Name: "daily-gate-rotation-156", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-157", Name: "daily-gate-rotation-157", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-158", Name: "daily-gate-rotation-158", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-159", Name: "daily-gate-rotation-159", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-160", Name: "daily-gate-rotation-160", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-161", Name: "daily-gate-rotation-161", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-162", Name: "daily-gate-rotation-162", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-163", Name: "daily-gate-rotation-163", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-164", Name: "daily-gate-rotation-164", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-165", Name: "daily-gate-rotation-165", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-166", Name: "daily-gate-rotation-166", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-167", Name: "daily-gate-rotation-167", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-168", Name: "daily-gate-rotation-168", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-169", Name: "daily-gate-rotation-169", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-170", Name: "daily-gate-rotation-170", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-171", Name: "daily-gate-rotation-171", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-172", Name: "daily-gate-rotation-172", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-173", Name: "daily-gate-rotation-173", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-174", Name: "daily-gate-rotation-174", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-175", Name: "daily-gate-rotation-175", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: false},
	{ID: "scenario-176", Name: "daily-gate-rotation-176", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-177", Name: "daily-gate-rotation-177", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-178", Name: "daily-gate-rotation-178", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-179", Name: "daily-gate-rotation-179", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
	{ID: "scenario-180", Name: "daily-gate-rotation-180", Steps: []string{"register", "select-parameters", "wrap", "persist", "audit", "recover"}, RequiresAudit: true},
}

func Scenarios() []Scenario {
	out := make([]Scenario, len(scenarios))
	copy(out, scenarios)
	return out
}
func ScenarioByID(id string) (Scenario, bool) {
	for _, s := range scenarios {
		if s.ID == id {
			return s, true
		}
	}
	return Scenario{}, false
}
func StepCount(id string) int {
	s, ok := ScenarioByID(id)
	if !ok {
		return 0
	}
	return len(s.Steps)
}
