package store

type ColumnSpec struct {
	Table    string
	Name     string
	Kind     string
	Indexed  bool
	Nullable bool
}

var columns = []ColumnSpec{
	{Table: "parameters", Name: "gateway_id-1", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "parameter_id-2", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "public_key-3", Kind: "text", Indexed: false, Nullable: true},
	{Table: "gateways", Name: "algorithm-4", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "fingerprint-5", Kind: "text", Indexed: true, Nullable: false},
	{Table: "sessions", Name: "active-6", Kind: "text", Indexed: false, Nullable: true},
	{Table: "audits", Name: "created_at-7", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "expires_at-8", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "wrapped_secret-9", Kind: "text", Indexed: false, Nullable: true},
	{Table: "sessions", Name: "state-10", Kind: "text", Indexed: true, Nullable: false},
	{Table: "audits", Name: "event-11", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "value-12", Kind: "text", Indexed: false, Nullable: true},
	{Table: "parameters", Name: "sequence-13", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "id-14", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "gateway_id-15", Kind: "text", Indexed: true, Nullable: true},
	{Table: "gateways", Name: "parameter_id-16", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "public_key-17", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "algorithm-18", Kind: "text", Indexed: false, Nullable: true},
	{Table: "audits", Name: "fingerprint-19", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "active-20", Kind: "text", Indexed: true, Nullable: false},
	{Table: "parameters", Name: "created_at-21", Kind: "text", Indexed: false, Nullable: true},
	{Table: "sessions", Name: "expires_at-22", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "wrapped_secret-23", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "state-24", Kind: "text", Indexed: false, Nullable: true},
	{Table: "parameters", Name: "event-25", Kind: "text", Indexed: true, Nullable: false},
	{Table: "sessions", Name: "value-26", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "sequence-27", Kind: "text", Indexed: false, Nullable: true},
	{Table: "gateways", Name: "id-28", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "gateway_id-29", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "parameter_id-30", Kind: "text", Indexed: true, Nullable: true},
	{Table: "audits", Name: "public_key-31", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "algorithm-32", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "fingerprint-33", Kind: "text", Indexed: false, Nullable: true},
	{Table: "sessions", Name: "active-34", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "created_at-35", Kind: "text", Indexed: true, Nullable: false},
	{Table: "gateways", Name: "expires_at-36", Kind: "text", Indexed: false, Nullable: true},
	{Table: "parameters", Name: "wrapped_secret-37", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "state-38", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "event-39", Kind: "text", Indexed: false, Nullable: true},
	{Table: "gateways", Name: "value-40", Kind: "text", Indexed: true, Nullable: false},
	{Table: "parameters", Name: "sequence-41", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "id-42", Kind: "text", Indexed: false, Nullable: true},
	{Table: "audits", Name: "gateway_id-43", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "parameter_id-44", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "public_key-45", Kind: "text", Indexed: true, Nullable: true},
	{Table: "sessions", Name: "algorithm-46", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "fingerprint-47", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "active-48", Kind: "text", Indexed: false, Nullable: true},
	{Table: "parameters", Name: "created_at-49", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "expires_at-50", Kind: "text", Indexed: true, Nullable: false},
	{Table: "audits", Name: "wrapped_secret-51", Kind: "text", Indexed: false, Nullable: true},
	{Table: "gateways", Name: "state-52", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "event-53", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "value-54", Kind: "text", Indexed: false, Nullable: true},
	{Table: "audits", Name: "sequence-55", Kind: "text", Indexed: true, Nullable: false},
	{Table: "gateways", Name: "id-56", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "gateway_id-57", Kind: "text", Indexed: false, Nullable: true},
	{Table: "sessions", Name: "parameter_id-58", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "public_key-59", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "algorithm-60", Kind: "text", Indexed: true, Nullable: true},
	{Table: "parameters", Name: "fingerprint-61", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "active-62", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "created_at-63", Kind: "text", Indexed: false, Nullable: true},
	{Table: "gateways", Name: "expires_at-64", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "wrapped_secret-65", Kind: "text", Indexed: true, Nullable: false},
	{Table: "sessions", Name: "state-66", Kind: "text", Indexed: false, Nullable: true},
	{Table: "audits", Name: "event-67", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "value-68", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "sequence-69", Kind: "text", Indexed: false, Nullable: true},
	{Table: "sessions", Name: "id-70", Kind: "text", Indexed: true, Nullable: false},
	{Table: "audits", Name: "gateway_id-71", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "parameter_id-72", Kind: "text", Indexed: false, Nullable: true},
	{Table: "parameters", Name: "public_key-73", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "algorithm-74", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "fingerprint-75", Kind: "text", Indexed: true, Nullable: true},
	{Table: "gateways", Name: "active-76", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "created_at-77", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "expires_at-78", Kind: "text", Indexed: false, Nullable: true},
	{Table: "audits", Name: "wrapped_secret-79", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "state-80", Kind: "text", Indexed: true, Nullable: false},
	{Table: "parameters", Name: "event-81", Kind: "text", Indexed: false, Nullable: true},
	{Table: "sessions", Name: "value-82", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "sequence-83", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "id-84", Kind: "text", Indexed: false, Nullable: true},
	{Table: "parameters", Name: "gateway_id-85", Kind: "text", Indexed: true, Nullable: false},
	{Table: "sessions", Name: "parameter_id-86", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "public_key-87", Kind: "text", Indexed: false, Nullable: true},
	{Table: "gateways", Name: "algorithm-88", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "fingerprint-89", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "active-90", Kind: "text", Indexed: true, Nullable: true},
	{Table: "audits", Name: "created_at-91", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "expires_at-92", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "wrapped_secret-93", Kind: "text", Indexed: false, Nullable: true},
	{Table: "sessions", Name: "state-94", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "event-95", Kind: "text", Indexed: true, Nullable: false},
	{Table: "gateways", Name: "value-96", Kind: "text", Indexed: false, Nullable: true},
	{Table: "parameters", Name: "sequence-97", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "id-98", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "gateway_id-99", Kind: "text", Indexed: false, Nullable: true},
	{Table: "gateways", Name: "parameter_id-100", Kind: "text", Indexed: true, Nullable: false},
	{Table: "parameters", Name: "public_key-101", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "algorithm-102", Kind: "text", Indexed: false, Nullable: true},
	{Table: "audits", Name: "fingerprint-103", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "active-104", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "created_at-105", Kind: "text", Indexed: true, Nullable: true},
	{Table: "sessions", Name: "expires_at-106", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "wrapped_secret-107", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "state-108", Kind: "text", Indexed: false, Nullable: true},
	{Table: "parameters", Name: "event-109", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "value-110", Kind: "text", Indexed: true, Nullable: false},
	{Table: "audits", Name: "sequence-111", Kind: "text", Indexed: false, Nullable: true},
	{Table: "gateways", Name: "id-112", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "gateway_id-113", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "parameter_id-114", Kind: "text", Indexed: false, Nullable: true},
	{Table: "audits", Name: "public_key-115", Kind: "text", Indexed: true, Nullable: false},
	{Table: "gateways", Name: "algorithm-116", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "fingerprint-117", Kind: "text", Indexed: false, Nullable: true},
	{Table: "sessions", Name: "active-118", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "created_at-119", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "expires_at-120", Kind: "text", Indexed: true, Nullable: true},
	{Table: "parameters", Name: "wrapped_secret-121", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "state-122", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "event-123", Kind: "text", Indexed: false, Nullable: true},
	{Table: "gateways", Name: "value-124", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "sequence-125", Kind: "text", Indexed: true, Nullable: false},
	{Table: "sessions", Name: "id-126", Kind: "text", Indexed: false, Nullable: true},
	{Table: "audits", Name: "gateway_id-127", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "parameter_id-128", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "public_key-129", Kind: "text", Indexed: false, Nullable: true},
	{Table: "sessions", Name: "algorithm-130", Kind: "text", Indexed: true, Nullable: false},
	{Table: "audits", Name: "fingerprint-131", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "active-132", Kind: "text", Indexed: false, Nullable: true},
	{Table: "parameters", Name: "created_at-133", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "expires_at-134", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "wrapped_secret-135", Kind: "text", Indexed: true, Nullable: true},
	{Table: "gateways", Name: "state-136", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "event-137", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "value-138", Kind: "text", Indexed: false, Nullable: true},
	{Table: "audits", Name: "sequence-139", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "id-140", Kind: "text", Indexed: true, Nullable: false},
	{Table: "parameters", Name: "gateway_id-141", Kind: "text", Indexed: false, Nullable: true},
	{Table: "sessions", Name: "parameter_id-142", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "public_key-143", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "algorithm-144", Kind: "text", Indexed: false, Nullable: true},
	{Table: "parameters", Name: "fingerprint-145", Kind: "text", Indexed: true, Nullable: false},
	{Table: "sessions", Name: "active-146", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "created_at-147", Kind: "text", Indexed: false, Nullable: true},
	{Table: "gateways", Name: "expires_at-148", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "wrapped_secret-149", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "state-150", Kind: "text", Indexed: true, Nullable: true},
	{Table: "audits", Name: "event-151", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "value-152", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "sequence-153", Kind: "text", Indexed: false, Nullable: true},
	{Table: "sessions", Name: "id-154", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "gateway_id-155", Kind: "text", Indexed: true, Nullable: false},
	{Table: "gateways", Name: "parameter_id-156", Kind: "text", Indexed: false, Nullable: true},
	{Table: "parameters", Name: "public_key-157", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "algorithm-158", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "fingerprint-159", Kind: "text", Indexed: false, Nullable: true},
	{Table: "gateways", Name: "active-160", Kind: "text", Indexed: true, Nullable: false},
	{Table: "parameters", Name: "created_at-161", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "expires_at-162", Kind: "text", Indexed: false, Nullable: true},
	{Table: "audits", Name: "wrapped_secret-163", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "state-164", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "event-165", Kind: "text", Indexed: true, Nullable: true},
	{Table: "sessions", Name: "value-166", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "sequence-167", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "id-168", Kind: "text", Indexed: false, Nullable: true},
	{Table: "parameters", Name: "gateway_id-169", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "parameter_id-170", Kind: "text", Indexed: true, Nullable: false},
	{Table: "audits", Name: "public_key-171", Kind: "text", Indexed: false, Nullable: true},
	{Table: "gateways", Name: "algorithm-172", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "fingerprint-173", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "active-174", Kind: "text", Indexed: false, Nullable: true},
	{Table: "audits", Name: "created_at-175", Kind: "text", Indexed: true, Nullable: false},
	{Table: "gateways", Name: "expires_at-176", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "wrapped_secret-177", Kind: "text", Indexed: false, Nullable: true},
	{Table: "sessions", Name: "state-178", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "event-179", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "value-180", Kind: "text", Indexed: true, Nullable: true},
	{Table: "parameters", Name: "sequence-181", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "id-182", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "gateway_id-183", Kind: "text", Indexed: false, Nullable: true},
	{Table: "gateways", Name: "parameter_id-184", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "public_key-185", Kind: "text", Indexed: true, Nullable: false},
	{Table: "sessions", Name: "algorithm-186", Kind: "text", Indexed: false, Nullable: true},
	{Table: "audits", Name: "fingerprint-187", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "active-188", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "created_at-189", Kind: "text", Indexed: false, Nullable: true},
	{Table: "sessions", Name: "expires_at-190", Kind: "text", Indexed: true, Nullable: false},
	{Table: "audits", Name: "wrapped_secret-191", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "state-192", Kind: "text", Indexed: false, Nullable: true},
	{Table: "parameters", Name: "event-193", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "value-194", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "sequence-195", Kind: "text", Indexed: true, Nullable: true},
	{Table: "gateways", Name: "id-196", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "gateway_id-197", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "parameter_id-198", Kind: "text", Indexed: false, Nullable: true},
	{Table: "audits", Name: "public_key-199", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "algorithm-200", Kind: "text", Indexed: true, Nullable: false},
	{Table: "parameters", Name: "fingerprint-201", Kind: "text", Indexed: false, Nullable: true},
	{Table: "sessions", Name: "active-202", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "created_at-203", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "expires_at-204", Kind: "text", Indexed: false, Nullable: true},
	{Table: "parameters", Name: "wrapped_secret-205", Kind: "text", Indexed: true, Nullable: false},
	{Table: "sessions", Name: "state-206", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "event-207", Kind: "text", Indexed: false, Nullable: true},
	{Table: "gateways", Name: "value-208", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "sequence-209", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "id-210", Kind: "text", Indexed: true, Nullable: true},
	{Table: "audits", Name: "gateway_id-211", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "parameter_id-212", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "public_key-213", Kind: "text", Indexed: false, Nullable: true},
	{Table: "sessions", Name: "algorithm-214", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "fingerprint-215", Kind: "text", Indexed: true, Nullable: false},
	{Table: "gateways", Name: "active-216", Kind: "text", Indexed: false, Nullable: true},
	{Table: "parameters", Name: "created_at-217", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "expires_at-218", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "wrapped_secret-219", Kind: "text", Indexed: false, Nullable: true},
	{Table: "gateways", Name: "state-220", Kind: "text", Indexed: true, Nullable: false},
	{Table: "parameters", Name: "event-221", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "value-222", Kind: "text", Indexed: false, Nullable: true},
	{Table: "audits", Name: "sequence-223", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "id-224", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "gateway_id-225", Kind: "text", Indexed: true, Nullable: true},
	{Table: "sessions", Name: "parameter_id-226", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "public_key-227", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "algorithm-228", Kind: "text", Indexed: false, Nullable: true},
	{Table: "parameters", Name: "fingerprint-229", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "active-230", Kind: "text", Indexed: true, Nullable: false},
	{Table: "audits", Name: "created_at-231", Kind: "text", Indexed: false, Nullable: true},
	{Table: "gateways", Name: "expires_at-232", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "wrapped_secret-233", Kind: "text", Indexed: false, Nullable: false},
	{Table: "sessions", Name: "state-234", Kind: "text", Indexed: false, Nullable: true},
	{Table: "audits", Name: "event-235", Kind: "text", Indexed: true, Nullable: false},
	{Table: "gateways", Name: "value-236", Kind: "text", Indexed: false, Nullable: false},
	{Table: "parameters", Name: "sequence-237", Kind: "text", Indexed: false, Nullable: true},
	{Table: "sessions", Name: "id-238", Kind: "text", Indexed: false, Nullable: false},
	{Table: "audits", Name: "gateway_id-239", Kind: "text", Indexed: false, Nullable: false},
	{Table: "gateways", Name: "parameter_id-240", Kind: "text", Indexed: true, Nullable: true},
}

func Columns() []ColumnSpec { out := make([]ColumnSpec, len(columns)); copy(out, columns); return out }
func ColumnsFor(table string) []ColumnSpec {
	out := make([]ColumnSpec, 0)
	for _, c := range columns {
		if c.Table == table {
			out = append(out, c)
		}
	}
	return out
}
func IndexedColumns() []ColumnSpec {
	out := make([]ColumnSpec, 0)
	for _, c := range columns {
		if c.Indexed {
			out = append(out, c)
		}
	}
	return out
}
