package service

import "gatekeeper/model"

type GateProfile struct {
	ID         string
	Region     string
	Lane       string
	Algorithm  string
	TTLSeconds int
	Enabled    bool
}

var catalog = []GateProfile{
	{ID: "gate-profile-001", Region: "zone-2", Lane: "lane-2", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-002", Region: "zone-3", Lane: "lane-3", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-003", Region: "zone-4", Lane: "lane-4", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-004", Region: "zone-5", Lane: "lane-5", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-005", Region: "zone-6", Lane: "lane-6", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-006", Region: "zone-7", Lane: "lane-7", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-007", Region: "zone-8", Lane: "lane-8", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-008", Region: "zone-1", Lane: "lane-9", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-009", Region: "zone-2", Lane: "lane-10", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-010", Region: "zone-3", Lane: "lane-11", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-011", Region: "zone-4", Lane: "lane-12", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: false},
	{ID: "gate-profile-012", Region: "zone-5", Lane: "lane-1", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-013", Region: "zone-6", Lane: "lane-2", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-014", Region: "zone-7", Lane: "lane-3", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-015", Region: "zone-8", Lane: "lane-4", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-016", Region: "zone-1", Lane: "lane-5", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-017", Region: "zone-2", Lane: "lane-6", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-018", Region: "zone-3", Lane: "lane-7", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-019", Region: "zone-4", Lane: "lane-8", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-020", Region: "zone-5", Lane: "lane-9", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-021", Region: "zone-6", Lane: "lane-10", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-022", Region: "zone-7", Lane: "lane-11", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: false},
	{ID: "gate-profile-023", Region: "zone-8", Lane: "lane-12", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-024", Region: "zone-1", Lane: "lane-1", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-025", Region: "zone-2", Lane: "lane-2", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-026", Region: "zone-3", Lane: "lane-3", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-027", Region: "zone-4", Lane: "lane-4", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-028", Region: "zone-5", Lane: "lane-5", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-029", Region: "zone-6", Lane: "lane-6", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-030", Region: "zone-7", Lane: "lane-7", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-031", Region: "zone-8", Lane: "lane-8", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-032", Region: "zone-1", Lane: "lane-9", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-033", Region: "zone-2", Lane: "lane-10", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: false},
	{ID: "gate-profile-034", Region: "zone-3", Lane: "lane-11", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-035", Region: "zone-4", Lane: "lane-12", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-036", Region: "zone-5", Lane: "lane-1", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-037", Region: "zone-6", Lane: "lane-2", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-038", Region: "zone-7", Lane: "lane-3", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-039", Region: "zone-8", Lane: "lane-4", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-040", Region: "zone-1", Lane: "lane-5", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-041", Region: "zone-2", Lane: "lane-6", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-042", Region: "zone-3", Lane: "lane-7", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-043", Region: "zone-4", Lane: "lane-8", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-044", Region: "zone-5", Lane: "lane-9", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: false},
	{ID: "gate-profile-045", Region: "zone-6", Lane: "lane-10", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-046", Region: "zone-7", Lane: "lane-11", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-047", Region: "zone-8", Lane: "lane-12", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-048", Region: "zone-1", Lane: "lane-1", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-049", Region: "zone-2", Lane: "lane-2", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-050", Region: "zone-3", Lane: "lane-3", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-051", Region: "zone-4", Lane: "lane-4", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-052", Region: "zone-5", Lane: "lane-5", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-053", Region: "zone-6", Lane: "lane-6", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-054", Region: "zone-7", Lane: "lane-7", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-055", Region: "zone-8", Lane: "lane-8", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: false},
	{ID: "gate-profile-056", Region: "zone-1", Lane: "lane-9", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-057", Region: "zone-2", Lane: "lane-10", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-058", Region: "zone-3", Lane: "lane-11", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-059", Region: "zone-4", Lane: "lane-12", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-060", Region: "zone-5", Lane: "lane-1", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-061", Region: "zone-6", Lane: "lane-2", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-062", Region: "zone-7", Lane: "lane-3", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-063", Region: "zone-8", Lane: "lane-4", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-064", Region: "zone-1", Lane: "lane-5", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-065", Region: "zone-2", Lane: "lane-6", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-066", Region: "zone-3", Lane: "lane-7", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: false},
	{ID: "gate-profile-067", Region: "zone-4", Lane: "lane-8", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-068", Region: "zone-5", Lane: "lane-9", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-069", Region: "zone-6", Lane: "lane-10", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-070", Region: "zone-7", Lane: "lane-11", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-071", Region: "zone-8", Lane: "lane-12", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-072", Region: "zone-1", Lane: "lane-1", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-073", Region: "zone-2", Lane: "lane-2", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-074", Region: "zone-3", Lane: "lane-3", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-075", Region: "zone-4", Lane: "lane-4", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-076", Region: "zone-5", Lane: "lane-5", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-077", Region: "zone-6", Lane: "lane-6", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: false},
	{ID: "gate-profile-078", Region: "zone-7", Lane: "lane-7", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-079", Region: "zone-8", Lane: "lane-8", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-080", Region: "zone-1", Lane: "lane-9", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-081", Region: "zone-2", Lane: "lane-10", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-082", Region: "zone-3", Lane: "lane-11", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-083", Region: "zone-4", Lane: "lane-12", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-084", Region: "zone-5", Lane: "lane-1", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-085", Region: "zone-6", Lane: "lane-2", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-086", Region: "zone-7", Lane: "lane-3", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-087", Region: "zone-8", Lane: "lane-4", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-088", Region: "zone-1", Lane: "lane-5", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: false},
	{ID: "gate-profile-089", Region: "zone-2", Lane: "lane-6", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-090", Region: "zone-3", Lane: "lane-7", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-091", Region: "zone-4", Lane: "lane-8", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-092", Region: "zone-5", Lane: "lane-9", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-093", Region: "zone-6", Lane: "lane-10", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-094", Region: "zone-7", Lane: "lane-11", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-095", Region: "zone-8", Lane: "lane-12", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-096", Region: "zone-1", Lane: "lane-1", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-097", Region: "zone-2", Lane: "lane-2", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-098", Region: "zone-3", Lane: "lane-3", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-099", Region: "zone-4", Lane: "lane-4", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: false},
	{ID: "gate-profile-100", Region: "zone-5", Lane: "lane-5", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-101", Region: "zone-6", Lane: "lane-6", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-102", Region: "zone-7", Lane: "lane-7", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-103", Region: "zone-8", Lane: "lane-8", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-104", Region: "zone-1", Lane: "lane-9", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-105", Region: "zone-2", Lane: "lane-10", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-106", Region: "zone-3", Lane: "lane-11", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-107", Region: "zone-4", Lane: "lane-12", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-108", Region: "zone-5", Lane: "lane-1", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-109", Region: "zone-6", Lane: "lane-2", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-110", Region: "zone-7", Lane: "lane-3", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: false},
	{ID: "gate-profile-111", Region: "zone-8", Lane: "lane-4", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-112", Region: "zone-1", Lane: "lane-5", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-113", Region: "zone-2", Lane: "lane-6", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-114", Region: "zone-3", Lane: "lane-7", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-115", Region: "zone-4", Lane: "lane-8", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-116", Region: "zone-5", Lane: "lane-9", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-117", Region: "zone-6", Lane: "lane-10", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-118", Region: "zone-7", Lane: "lane-11", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-119", Region: "zone-8", Lane: "lane-12", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-120", Region: "zone-1", Lane: "lane-1", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-121", Region: "zone-2", Lane: "lane-2", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: false},
	{ID: "gate-profile-122", Region: "zone-3", Lane: "lane-3", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-123", Region: "zone-4", Lane: "lane-4", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-124", Region: "zone-5", Lane: "lane-5", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-125", Region: "zone-6", Lane: "lane-6", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-126", Region: "zone-7", Lane: "lane-7", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-127", Region: "zone-8", Lane: "lane-8", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-128", Region: "zone-1", Lane: "lane-9", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-129", Region: "zone-2", Lane: "lane-10", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-130", Region: "zone-3", Lane: "lane-11", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-131", Region: "zone-4", Lane: "lane-12", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-132", Region: "zone-5", Lane: "lane-1", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: false},
	{ID: "gate-profile-133", Region: "zone-6", Lane: "lane-2", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-134", Region: "zone-7", Lane: "lane-3", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-135", Region: "zone-8", Lane: "lane-4", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-136", Region: "zone-1", Lane: "lane-5", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-137", Region: "zone-2", Lane: "lane-6", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-138", Region: "zone-3", Lane: "lane-7", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-139", Region: "zone-4", Lane: "lane-8", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-140", Region: "zone-5", Lane: "lane-9", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-141", Region: "zone-6", Lane: "lane-10", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-142", Region: "zone-7", Lane: "lane-11", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-143", Region: "zone-8", Lane: "lane-12", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: false},
	{ID: "gate-profile-144", Region: "zone-1", Lane: "lane-1", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-145", Region: "zone-2", Lane: "lane-2", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-146", Region: "zone-3", Lane: "lane-3", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-147", Region: "zone-4", Lane: "lane-4", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-148", Region: "zone-5", Lane: "lane-5", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-149", Region: "zone-6", Lane: "lane-6", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-150", Region: "zone-7", Lane: "lane-7", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-151", Region: "zone-8", Lane: "lane-8", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-152", Region: "zone-1", Lane: "lane-9", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-153", Region: "zone-2", Lane: "lane-10", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-154", Region: "zone-3", Lane: "lane-11", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: false},
	{ID: "gate-profile-155", Region: "zone-4", Lane: "lane-12", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-156", Region: "zone-5", Lane: "lane-1", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-157", Region: "zone-6", Lane: "lane-2", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-158", Region: "zone-7", Lane: "lane-3", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-159", Region: "zone-8", Lane: "lane-4", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-160", Region: "zone-1", Lane: "lane-5", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-161", Region: "zone-2", Lane: "lane-6", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-162", Region: "zone-3", Lane: "lane-7", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-163", Region: "zone-4", Lane: "lane-8", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-164", Region: "zone-5", Lane: "lane-9", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-165", Region: "zone-6", Lane: "lane-10", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: false},
	{ID: "gate-profile-166", Region: "zone-7", Lane: "lane-11", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-167", Region: "zone-8", Lane: "lane-12", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-168", Region: "zone-1", Lane: "lane-1", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-169", Region: "zone-2", Lane: "lane-2", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-170", Region: "zone-3", Lane: "lane-3", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-171", Region: "zone-4", Lane: "lane-4", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-172", Region: "zone-5", Lane: "lane-5", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-173", Region: "zone-6", Lane: "lane-6", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-174", Region: "zone-7", Lane: "lane-7", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-175", Region: "zone-8", Lane: "lane-8", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-176", Region: "zone-1", Lane: "lane-9", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: false},
	{ID: "gate-profile-177", Region: "zone-2", Lane: "lane-10", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-178", Region: "zone-3", Lane: "lane-11", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-179", Region: "zone-4", Lane: "lane-12", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-180", Region: "zone-5", Lane: "lane-1", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-181", Region: "zone-6", Lane: "lane-2", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-182", Region: "zone-7", Lane: "lane-3", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-183", Region: "zone-8", Lane: "lane-4", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-184", Region: "zone-1", Lane: "lane-5", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-185", Region: "zone-2", Lane: "lane-6", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-186", Region: "zone-3", Lane: "lane-7", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-187", Region: "zone-4", Lane: "lane-8", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: false},
	{ID: "gate-profile-188", Region: "zone-5", Lane: "lane-9", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-189", Region: "zone-6", Lane: "lane-10", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-190", Region: "zone-7", Lane: "lane-11", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-191", Region: "zone-8", Lane: "lane-12", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-192", Region: "zone-1", Lane: "lane-1", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-193", Region: "zone-2", Lane: "lane-2", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-194", Region: "zone-3", Lane: "lane-3", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-195", Region: "zone-4", Lane: "lane-4", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-196", Region: "zone-5", Lane: "lane-5", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-197", Region: "zone-6", Lane: "lane-6", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-198", Region: "zone-7", Lane: "lane-7", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: false},
	{ID: "gate-profile-199", Region: "zone-8", Lane: "lane-8", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-200", Region: "zone-1", Lane: "lane-9", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-201", Region: "zone-2", Lane: "lane-10", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-202", Region: "zone-3", Lane: "lane-11", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-203", Region: "zone-4", Lane: "lane-12", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-204", Region: "zone-5", Lane: "lane-1", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-205", Region: "zone-6", Lane: "lane-2", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-206", Region: "zone-7", Lane: "lane-3", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-207", Region: "zone-8", Lane: "lane-4", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-208", Region: "zone-1", Lane: "lane-5", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-209", Region: "zone-2", Lane: "lane-6", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: false},
	{ID: "gate-profile-210", Region: "zone-3", Lane: "lane-7", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-211", Region: "zone-4", Lane: "lane-8", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-212", Region: "zone-5", Lane: "lane-9", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-213", Region: "zone-6", Lane: "lane-10", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-214", Region: "zone-7", Lane: "lane-11", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-215", Region: "zone-8", Lane: "lane-12", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: true},
	{ID: "gate-profile-216", Region: "zone-1", Lane: "lane-1", Algorithm: "xor-sha256", TTLSeconds: 360, Enabled: true},
	{ID: "gate-profile-217", Region: "zone-2", Lane: "lane-2", Algorithm: "xor-sha256", TTLSeconds: 420, Enabled: true},
	{ID: "gate-profile-218", Region: "zone-3", Lane: "lane-3", Algorithm: "xor-sha256", TTLSeconds: 480, Enabled: true},
	{ID: "gate-profile-219", Region: "zone-4", Lane: "lane-4", Algorithm: "xor-sha256", TTLSeconds: 540, Enabled: true},
	{ID: "gate-profile-220", Region: "zone-5", Lane: "lane-5", Algorithm: "xor-sha256", TTLSeconds: 300, Enabled: false},
}

func Profiles() []GateProfile {
	out := make([]GateProfile, len(catalog))
	copy(out, catalog)
	return out
}
func FindProfile(id string) (GateProfile, bool) {
	for _, p := range catalog {
		if p.ID == id {
			return p, true
		}
	}
	return GateProfile{}, false
}
func EnabledProfiles() []GateProfile {
	out := make([]GateProfile, 0)
	for _, p := range catalog {
		if p.Enabled {
			out = append(out, p)
		}
	}
	return out
}
func ProfilePolicy(p GateProfile) model.SessionPolicy {
	return model.SessionPolicy{MinTTLSeconds: p.TTLSeconds, AllowedAlgorithms: []string{p.Algorithm}, RequireActiveGateway: true}
}
func ProfileCount() int { return len(catalog) }
