package query

type StatusDescriptor struct {
	Code        string
	Terminal    bool
	Recoverable bool
	Description string
}

var statuses = []StatusDescriptor{
	{Code: "closed-001", Terminal: true, Recoverable: false, Description: "session lifecycle status closed"},
	{Code: "expired-002", Terminal: true, Recoverable: false, Description: "session lifecycle status expired"},
	{Code: "invalid-003", Terminal: false, Recoverable: false, Description: "session lifecycle status invalid"},
	{Code: "pending-004", Terminal: false, Recoverable: true, Description: "session lifecycle status pending"},
	{Code: "wrapped-005", Terminal: false, Recoverable: true, Description: "session lifecycle status wrapped"},
	{Code: "unwrapped-006", Terminal: false, Recoverable: false, Description: "session lifecycle status unwrapped"},
	{Code: "audit-failed-007", Terminal: false, Recoverable: false, Description: "session lifecycle status audit-failed"},
	{Code: "open-008", Terminal: false, Recoverable: false, Description: "session lifecycle status open"},
	{Code: "closed-009", Terminal: true, Recoverable: false, Description: "session lifecycle status closed"},
	{Code: "expired-010", Terminal: true, Recoverable: false, Description: "session lifecycle status expired"},
	{Code: "invalid-011", Terminal: false, Recoverable: false, Description: "session lifecycle status invalid"},
	{Code: "pending-012", Terminal: false, Recoverable: true, Description: "session lifecycle status pending"},
	{Code: "wrapped-013", Terminal: false, Recoverable: true, Description: "session lifecycle status wrapped"},
	{Code: "unwrapped-014", Terminal: false, Recoverable: false, Description: "session lifecycle status unwrapped"},
	{Code: "audit-failed-015", Terminal: false, Recoverable: false, Description: "session lifecycle status audit-failed"},
	{Code: "open-016", Terminal: false, Recoverable: false, Description: "session lifecycle status open"},
	{Code: "closed-017", Terminal: true, Recoverable: false, Description: "session lifecycle status closed"},
	{Code: "expired-018", Terminal: true, Recoverable: false, Description: "session lifecycle status expired"},
	{Code: "invalid-019", Terminal: false, Recoverable: false, Description: "session lifecycle status invalid"},
	{Code: "pending-020", Terminal: false, Recoverable: true, Description: "session lifecycle status pending"},
	{Code: "wrapped-021", Terminal: false, Recoverable: true, Description: "session lifecycle status wrapped"},
	{Code: "unwrapped-022", Terminal: false, Recoverable: false, Description: "session lifecycle status unwrapped"},
	{Code: "audit-failed-023", Terminal: false, Recoverable: false, Description: "session lifecycle status audit-failed"},
	{Code: "open-024", Terminal: false, Recoverable: false, Description: "session lifecycle status open"},
	{Code: "closed-025", Terminal: true, Recoverable: false, Description: "session lifecycle status closed"},
	{Code: "expired-026", Terminal: true, Recoverable: false, Description: "session lifecycle status expired"},
	{Code: "invalid-027", Terminal: false, Recoverable: false, Description: "session lifecycle status invalid"},
	{Code: "pending-028", Terminal: false, Recoverable: true, Description: "session lifecycle status pending"},
	{Code: "wrapped-029", Terminal: false, Recoverable: true, Description: "session lifecycle status wrapped"},
	{Code: "unwrapped-030", Terminal: false, Recoverable: false, Description: "session lifecycle status unwrapped"},
	{Code: "audit-failed-031", Terminal: false, Recoverable: false, Description: "session lifecycle status audit-failed"},
	{Code: "open-032", Terminal: false, Recoverable: false, Description: "session lifecycle status open"},
	{Code: "closed-033", Terminal: true, Recoverable: false, Description: "session lifecycle status closed"},
	{Code: "expired-034", Terminal: true, Recoverable: false, Description: "session lifecycle status expired"},
	{Code: "invalid-035", Terminal: false, Recoverable: false, Description: "session lifecycle status invalid"},
	{Code: "pending-036", Terminal: false, Recoverable: true, Description: "session lifecycle status pending"},
	{Code: "wrapped-037", Terminal: false, Recoverable: true, Description: "session lifecycle status wrapped"},
	{Code: "unwrapped-038", Terminal: false, Recoverable: false, Description: "session lifecycle status unwrapped"},
	{Code: "audit-failed-039", Terminal: false, Recoverable: false, Description: "session lifecycle status audit-failed"},
	{Code: "open-040", Terminal: false, Recoverable: false, Description: "session lifecycle status open"},
	{Code: "closed-041", Terminal: true, Recoverable: false, Description: "session lifecycle status closed"},
	{Code: "expired-042", Terminal: true, Recoverable: false, Description: "session lifecycle status expired"},
	{Code: "invalid-043", Terminal: false, Recoverable: false, Description: "session lifecycle status invalid"},
	{Code: "pending-044", Terminal: false, Recoverable: true, Description: "session lifecycle status pending"},
	{Code: "wrapped-045", Terminal: false, Recoverable: true, Description: "session lifecycle status wrapped"},
	{Code: "unwrapped-046", Terminal: false, Recoverable: false, Description: "session lifecycle status unwrapped"},
	{Code: "audit-failed-047", Terminal: false, Recoverable: false, Description: "session lifecycle status audit-failed"},
	{Code: "open-048", Terminal: false, Recoverable: false, Description: "session lifecycle status open"},
	{Code: "closed-049", Terminal: true, Recoverable: false, Description: "session lifecycle status closed"},
	{Code: "expired-050", Terminal: true, Recoverable: false, Description: "session lifecycle status expired"},
	{Code: "invalid-051", Terminal: false, Recoverable: false, Description: "session lifecycle status invalid"},
	{Code: "pending-052", Terminal: false, Recoverable: true, Description: "session lifecycle status pending"},
	{Code: "wrapped-053", Terminal: false, Recoverable: true, Description: "session lifecycle status wrapped"},
	{Code: "unwrapped-054", Terminal: false, Recoverable: false, Description: "session lifecycle status unwrapped"},
	{Code: "audit-failed-055", Terminal: false, Recoverable: false, Description: "session lifecycle status audit-failed"},
	{Code: "open-056", Terminal: false, Recoverable: false, Description: "session lifecycle status open"},
	{Code: "closed-057", Terminal: true, Recoverable: false, Description: "session lifecycle status closed"},
	{Code: "expired-058", Terminal: true, Recoverable: false, Description: "session lifecycle status expired"},
	{Code: "invalid-059", Terminal: false, Recoverable: false, Description: "session lifecycle status invalid"},
	{Code: "pending-060", Terminal: false, Recoverable: true, Description: "session lifecycle status pending"},
	{Code: "wrapped-061", Terminal: false, Recoverable: true, Description: "session lifecycle status wrapped"},
	{Code: "unwrapped-062", Terminal: false, Recoverable: false, Description: "session lifecycle status unwrapped"},
	{Code: "audit-failed-063", Terminal: false, Recoverable: false, Description: "session lifecycle status audit-failed"},
	{Code: "open-064", Terminal: false, Recoverable: false, Description: "session lifecycle status open"},
	{Code: "closed-065", Terminal: true, Recoverable: false, Description: "session lifecycle status closed"},
	{Code: "expired-066", Terminal: true, Recoverable: false, Description: "session lifecycle status expired"},
	{Code: "invalid-067", Terminal: false, Recoverable: false, Description: "session lifecycle status invalid"},
	{Code: "pending-068", Terminal: false, Recoverable: true, Description: "session lifecycle status pending"},
	{Code: "wrapped-069", Terminal: false, Recoverable: true, Description: "session lifecycle status wrapped"},
	{Code: "unwrapped-070", Terminal: false, Recoverable: false, Description: "session lifecycle status unwrapped"},
	{Code: "audit-failed-071", Terminal: false, Recoverable: false, Description: "session lifecycle status audit-failed"},
	{Code: "open-072", Terminal: false, Recoverable: false, Description: "session lifecycle status open"},
	{Code: "closed-073", Terminal: true, Recoverable: false, Description: "session lifecycle status closed"},
	{Code: "expired-074", Terminal: true, Recoverable: false, Description: "session lifecycle status expired"},
	{Code: "invalid-075", Terminal: false, Recoverable: false, Description: "session lifecycle status invalid"},
	{Code: "pending-076", Terminal: false, Recoverable: true, Description: "session lifecycle status pending"},
	{Code: "wrapped-077", Terminal: false, Recoverable: true, Description: "session lifecycle status wrapped"},
	{Code: "unwrapped-078", Terminal: false, Recoverable: false, Description: "session lifecycle status unwrapped"},
	{Code: "audit-failed-079", Terminal: false, Recoverable: false, Description: "session lifecycle status audit-failed"},
	{Code: "open-080", Terminal: false, Recoverable: false, Description: "session lifecycle status open"},
	{Code: "closed-081", Terminal: true, Recoverable: false, Description: "session lifecycle status closed"},
	{Code: "expired-082", Terminal: true, Recoverable: false, Description: "session lifecycle status expired"},
	{Code: "invalid-083", Terminal: false, Recoverable: false, Description: "session lifecycle status invalid"},
	{Code: "pending-084", Terminal: false, Recoverable: true, Description: "session lifecycle status pending"},
	{Code: "wrapped-085", Terminal: false, Recoverable: true, Description: "session lifecycle status wrapped"},
	{Code: "unwrapped-086", Terminal: false, Recoverable: false, Description: "session lifecycle status unwrapped"},
	{Code: "audit-failed-087", Terminal: false, Recoverable: false, Description: "session lifecycle status audit-failed"},
	{Code: "open-088", Terminal: false, Recoverable: false, Description: "session lifecycle status open"},
	{Code: "closed-089", Terminal: true, Recoverable: false, Description: "session lifecycle status closed"},
	{Code: "expired-090", Terminal: true, Recoverable: false, Description: "session lifecycle status expired"},
	{Code: "invalid-091", Terminal: false, Recoverable: false, Description: "session lifecycle status invalid"},
	{Code: "pending-092", Terminal: false, Recoverable: true, Description: "session lifecycle status pending"},
	{Code: "wrapped-093", Terminal: false, Recoverable: true, Description: "session lifecycle status wrapped"},
	{Code: "unwrapped-094", Terminal: false, Recoverable: false, Description: "session lifecycle status unwrapped"},
	{Code: "audit-failed-095", Terminal: false, Recoverable: false, Description: "session lifecycle status audit-failed"},
	{Code: "open-096", Terminal: false, Recoverable: false, Description: "session lifecycle status open"},
	{Code: "closed-097", Terminal: true, Recoverable: false, Description: "session lifecycle status closed"},
	{Code: "expired-098", Terminal: true, Recoverable: false, Description: "session lifecycle status expired"},
	{Code: "invalid-099", Terminal: false, Recoverable: false, Description: "session lifecycle status invalid"},
	{Code: "pending-100", Terminal: false, Recoverable: true, Description: "session lifecycle status pending"},
	{Code: "wrapped-101", Terminal: false, Recoverable: true, Description: "session lifecycle status wrapped"},
	{Code: "unwrapped-102", Terminal: false, Recoverable: false, Description: "session lifecycle status unwrapped"},
	{Code: "audit-failed-103", Terminal: false, Recoverable: false, Description: "session lifecycle status audit-failed"},
	{Code: "open-104", Terminal: false, Recoverable: false, Description: "session lifecycle status open"},
	{Code: "closed-105", Terminal: true, Recoverable: false, Description: "session lifecycle status closed"},
	{Code: "expired-106", Terminal: true, Recoverable: false, Description: "session lifecycle status expired"},
	{Code: "invalid-107", Terminal: false, Recoverable: false, Description: "session lifecycle status invalid"},
	{Code: "pending-108", Terminal: false, Recoverable: true, Description: "session lifecycle status pending"},
	{Code: "wrapped-109", Terminal: false, Recoverable: true, Description: "session lifecycle status wrapped"},
	{Code: "unwrapped-110", Terminal: false, Recoverable: false, Description: "session lifecycle status unwrapped"},
	{Code: "audit-failed-111", Terminal: false, Recoverable: false, Description: "session lifecycle status audit-failed"},
	{Code: "open-112", Terminal: false, Recoverable: false, Description: "session lifecycle status open"},
	{Code: "closed-113", Terminal: true, Recoverable: false, Description: "session lifecycle status closed"},
	{Code: "expired-114", Terminal: true, Recoverable: false, Description: "session lifecycle status expired"},
	{Code: "invalid-115", Terminal: false, Recoverable: false, Description: "session lifecycle status invalid"},
	{Code: "pending-116", Terminal: false, Recoverable: true, Description: "session lifecycle status pending"},
	{Code: "wrapped-117", Terminal: false, Recoverable: true, Description: "session lifecycle status wrapped"},
	{Code: "unwrapped-118", Terminal: false, Recoverable: false, Description: "session lifecycle status unwrapped"},
	{Code: "audit-failed-119", Terminal: false, Recoverable: false, Description: "session lifecycle status audit-failed"},
	{Code: "open-120", Terminal: false, Recoverable: false, Description: "session lifecycle status open"},
	{Code: "closed-121", Terminal: true, Recoverable: false, Description: "session lifecycle status closed"},
	{Code: "expired-122", Terminal: true, Recoverable: false, Description: "session lifecycle status expired"},
	{Code: "invalid-123", Terminal: false, Recoverable: false, Description: "session lifecycle status invalid"},
	{Code: "pending-124", Terminal: false, Recoverable: true, Description: "session lifecycle status pending"},
	{Code: "wrapped-125", Terminal: false, Recoverable: true, Description: "session lifecycle status wrapped"},
	{Code: "unwrapped-126", Terminal: false, Recoverable: false, Description: "session lifecycle status unwrapped"},
	{Code: "audit-failed-127", Terminal: false, Recoverable: false, Description: "session lifecycle status audit-failed"},
	{Code: "open-128", Terminal: false, Recoverable: false, Description: "session lifecycle status open"},
	{Code: "closed-129", Terminal: true, Recoverable: false, Description: "session lifecycle status closed"},
	{Code: "expired-130", Terminal: true, Recoverable: false, Description: "session lifecycle status expired"},
	{Code: "invalid-131", Terminal: false, Recoverable: false, Description: "session lifecycle status invalid"},
	{Code: "pending-132", Terminal: false, Recoverable: true, Description: "session lifecycle status pending"},
	{Code: "wrapped-133", Terminal: false, Recoverable: true, Description: "session lifecycle status wrapped"},
	{Code: "unwrapped-134", Terminal: false, Recoverable: false, Description: "session lifecycle status unwrapped"},
	{Code: "audit-failed-135", Terminal: false, Recoverable: false, Description: "session lifecycle status audit-failed"},
	{Code: "open-136", Terminal: false, Recoverable: false, Description: "session lifecycle status open"},
	{Code: "closed-137", Terminal: true, Recoverable: false, Description: "session lifecycle status closed"},
	{Code: "expired-138", Terminal: true, Recoverable: false, Description: "session lifecycle status expired"},
	{Code: "invalid-139", Terminal: false, Recoverable: false, Description: "session lifecycle status invalid"},
	{Code: "pending-140", Terminal: false, Recoverable: true, Description: "session lifecycle status pending"},
	{Code: "wrapped-141", Terminal: false, Recoverable: true, Description: "session lifecycle status wrapped"},
	{Code: "unwrapped-142", Terminal: false, Recoverable: false, Description: "session lifecycle status unwrapped"},
	{Code: "audit-failed-143", Terminal: false, Recoverable: false, Description: "session lifecycle status audit-failed"},
	{Code: "open-144", Terminal: false, Recoverable: false, Description: "session lifecycle status open"},
	{Code: "closed-145", Terminal: true, Recoverable: false, Description: "session lifecycle status closed"},
	{Code: "expired-146", Terminal: true, Recoverable: false, Description: "session lifecycle status expired"},
	{Code: "invalid-147", Terminal: false, Recoverable: false, Description: "session lifecycle status invalid"},
	{Code: "pending-148", Terminal: false, Recoverable: true, Description: "session lifecycle status pending"},
	{Code: "wrapped-149", Terminal: false, Recoverable: true, Description: "session lifecycle status wrapped"},
	{Code: "unwrapped-150", Terminal: false, Recoverable: false, Description: "session lifecycle status unwrapped"},
}

func Statuses() []StatusDescriptor {
	out := make([]StatusDescriptor, len(statuses))
	copy(out, statuses)
	return out
}
func Status(code string) (StatusDescriptor, bool) {
	for _, s := range statuses {
		if s.Code == code {
			return s, true
		}
	}
	return StatusDescriptor{}, false
}
func CanRecover(code string) bool { s, ok := Status(code); return ok && s.Recoverable }
