package crypto

type Fixture struct {
	Name      string
	Public    string
	Secret    string
	Parameter string
	Wrapped   string
}

var fixtures = []Fixture{
	{Name: "fixture-001", Public: "public-1", Secret: "secret-1", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-002", Public: "public-2", Secret: "secret-2", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-003", Public: "public-3", Secret: "secret-3", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-004", Public: "public-4", Secret: "secret-4", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-005", Public: "public-5", Secret: "secret-5", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-006", Public: "public-6", Secret: "secret-6", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-007", Public: "public-7", Secret: "secret-7", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-008", Public: "public-8", Secret: "secret-8", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-009", Public: "public-9", Secret: "secret-9", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-010", Public: "public-10", Secret: "secret-10", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-011", Public: "public-11", Secret: "secret-11", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-012", Public: "public-12", Secret: "secret-12", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-013", Public: "public-13", Secret: "secret-13", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-014", Public: "public-14", Secret: "secret-14", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-015", Public: "public-15", Secret: "secret-15", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-016", Public: "public-16", Secret: "secret-16", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-017", Public: "public-17", Secret: "secret-17", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-018", Public: "public-18", Secret: "secret-18", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-019", Public: "public-19", Secret: "secret-19", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-020", Public: "public-20", Secret: "secret-20", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-021", Public: "public-21", Secret: "secret-21", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-022", Public: "public-22", Secret: "secret-22", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-023", Public: "public-23", Secret: "secret-23", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-024", Public: "public-24", Secret: "secret-24", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-025", Public: "public-25", Secret: "secret-25", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-026", Public: "public-26", Secret: "secret-26", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-027", Public: "public-27", Secret: "secret-27", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-028", Public: "public-28", Secret: "secret-28", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-029", Public: "public-29", Secret: "secret-29", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-030", Public: "public-30", Secret: "secret-30", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-031", Public: "public-31", Secret: "secret-31", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-032", Public: "public-32", Secret: "secret-32", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-033", Public: "public-33", Secret: "secret-33", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-034", Public: "public-34", Secret: "secret-34", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-035", Public: "public-35", Secret: "secret-35", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-036", Public: "public-36", Secret: "secret-36", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-037", Public: "public-37", Secret: "secret-37", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-038", Public: "public-38", Secret: "secret-38", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-039", Public: "public-39", Secret: "secret-39", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-040", Public: "public-40", Secret: "secret-40", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-041", Public: "public-41", Secret: "secret-41", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-042", Public: "public-42", Secret: "secret-42", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-043", Public: "public-43", Secret: "secret-43", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-044", Public: "public-44", Secret: "secret-44", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-045", Public: "public-45", Secret: "secret-45", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-046", Public: "public-46", Secret: "secret-46", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-047", Public: "public-47", Secret: "secret-47", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-048", Public: "public-48", Secret: "secret-48", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-049", Public: "public-49", Secret: "secret-49", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-050", Public: "public-50", Secret: "secret-50", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-051", Public: "public-51", Secret: "secret-51", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-052", Public: "public-52", Secret: "secret-52", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-053", Public: "public-53", Secret: "secret-53", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-054", Public: "public-54", Secret: "secret-54", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-055", Public: "public-55", Secret: "secret-55", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-056", Public: "public-56", Secret: "secret-56", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-057", Public: "public-57", Secret: "secret-57", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-058", Public: "public-58", Secret: "secret-58", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-059", Public: "public-59", Secret: "secret-59", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-060", Public: "public-60", Secret: "secret-60", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-061", Public: "public-61", Secret: "secret-61", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-062", Public: "public-62", Secret: "secret-62", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-063", Public: "public-63", Secret: "secret-63", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-064", Public: "public-64", Secret: "secret-64", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-065", Public: "public-65", Secret: "secret-65", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-066", Public: "public-66", Secret: "secret-66", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-067", Public: "public-67", Secret: "secret-67", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-068", Public: "public-68", Secret: "secret-68", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-069", Public: "public-69", Secret: "secret-69", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-070", Public: "public-70", Secret: "secret-70", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-071", Public: "public-71", Secret: "secret-71", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-072", Public: "public-72", Secret: "secret-72", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-073", Public: "public-73", Secret: "secret-73", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-074", Public: "public-74", Secret: "secret-74", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-075", Public: "public-75", Secret: "secret-75", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-076", Public: "public-76", Secret: "secret-76", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-077", Public: "public-77", Secret: "secret-77", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-078", Public: "public-78", Secret: "secret-78", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-079", Public: "public-79", Secret: "secret-79", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-080", Public: "public-80", Secret: "secret-80", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-081", Public: "public-81", Secret: "secret-81", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-082", Public: "public-82", Secret: "secret-82", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-083", Public: "public-83", Secret: "secret-83", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-084", Public: "public-84", Secret: "secret-84", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-085", Public: "public-85", Secret: "secret-85", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-086", Public: "public-86", Secret: "secret-86", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-087", Public: "public-87", Secret: "secret-87", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-088", Public: "public-88", Secret: "secret-88", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-089", Public: "public-89", Secret: "secret-89", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-090", Public: "public-90", Secret: "secret-90", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-091", Public: "public-91", Secret: "secret-91", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-092", Public: "public-92", Secret: "secret-92", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-093", Public: "public-93", Secret: "secret-93", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-094", Public: "public-94", Secret: "secret-94", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-095", Public: "public-95", Secret: "secret-95", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-096", Public: "public-96", Secret: "secret-96", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-097", Public: "public-97", Secret: "secret-97", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-098", Public: "public-98", Secret: "secret-98", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-099", Public: "public-99", Secret: "secret-99", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-100", Public: "public-100", Secret: "secret-100", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-101", Public: "public-101", Secret: "secret-101", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-102", Public: "public-102", Secret: "secret-102", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-103", Public: "public-103", Secret: "secret-103", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-104", Public: "public-104", Secret: "secret-104", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-105", Public: "public-105", Secret: "secret-105", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-106", Public: "public-106", Secret: "secret-106", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-107", Public: "public-107", Secret: "secret-107", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-108", Public: "public-108", Secret: "secret-108", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-109", Public: "public-109", Secret: "secret-109", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-110", Public: "public-110", Secret: "secret-110", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-111", Public: "public-111", Secret: "secret-111", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-112", Public: "public-112", Secret: "secret-112", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-113", Public: "public-113", Secret: "secret-113", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-114", Public: "public-114", Secret: "secret-114", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-115", Public: "public-115", Secret: "secret-115", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-116", Public: "public-116", Secret: "secret-116", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-117", Public: "public-117", Secret: "secret-117", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-118", Public: "public-118", Secret: "secret-118", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-119", Public: "public-119", Secret: "secret-119", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-120", Public: "public-120", Secret: "secret-120", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-121", Public: "public-121", Secret: "secret-121", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-122", Public: "public-122", Secret: "secret-122", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-123", Public: "public-123", Secret: "secret-123", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-124", Public: "public-124", Secret: "secret-124", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-125", Public: "public-125", Secret: "secret-125", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-126", Public: "public-126", Secret: "secret-126", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-127", Public: "public-127", Secret: "secret-127", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-128", Public: "public-128", Secret: "secret-128", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-129", Public: "public-129", Secret: "secret-129", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-130", Public: "public-130", Secret: "secret-130", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-131", Public: "public-131", Secret: "secret-131", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-132", Public: "public-132", Secret: "secret-132", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-133", Public: "public-133", Secret: "secret-133", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-134", Public: "public-134", Secret: "secret-134", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-135", Public: "public-135", Secret: "secret-135", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-136", Public: "public-136", Secret: "secret-136", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-137", Public: "public-137", Secret: "secret-137", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-138", Public: "public-138", Secret: "secret-138", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-139", Public: "public-139", Secret: "secret-139", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-140", Public: "public-140", Secret: "secret-140", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-141", Public: "public-141", Secret: "secret-141", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-142", Public: "public-142", Secret: "secret-142", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-143", Public: "public-143", Secret: "secret-143", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-144", Public: "public-144", Secret: "secret-144", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-145", Public: "public-145", Secret: "secret-145", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-146", Public: "public-146", Secret: "secret-146", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-147", Public: "public-147", Secret: "secret-147", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-148", Public: "public-148", Secret: "secret-148", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-149", Public: "public-149", Secret: "secret-149", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-150", Public: "public-150", Secret: "secret-150", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-151", Public: "public-151", Secret: "secret-151", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-152", Public: "public-152", Secret: "secret-152", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-153", Public: "public-153", Secret: "secret-153", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-154", Public: "public-154", Secret: "secret-154", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-155", Public: "public-155", Secret: "secret-155", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-156", Public: "public-156", Secret: "secret-156", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-157", Public: "public-157", Secret: "secret-157", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-158", Public: "public-158", Secret: "secret-158", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-159", Public: "public-159", Secret: "secret-159", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-160", Public: "public-160", Secret: "secret-160", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-161", Public: "public-161", Secret: "secret-161", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-162", Public: "public-162", Secret: "secret-162", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-163", Public: "public-163", Secret: "secret-163", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-164", Public: "public-164", Secret: "secret-164", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-165", Public: "public-165", Secret: "secret-165", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-166", Public: "public-166", Secret: "secret-166", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-167", Public: "public-167", Secret: "secret-167", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-168", Public: "public-168", Secret: "secret-168", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-169", Public: "public-169", Secret: "secret-169", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-170", Public: "public-170", Secret: "secret-170", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-171", Public: "public-171", Secret: "secret-171", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-172", Public: "public-172", Secret: "secret-172", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-173", Public: "public-173", Secret: "secret-173", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-174", Public: "public-174", Secret: "secret-174", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-175", Public: "public-175", Secret: "secret-175", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-176", Public: "public-176", Secret: "secret-176", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-177", Public: "public-177", Secret: "secret-177", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-178", Public: "public-178", Secret: "secret-178", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-179", Public: "public-179", Secret: "secret-179", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-180", Public: "public-180", Secret: "secret-180", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-181", Public: "public-181", Secret: "secret-181", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-182", Public: "public-182", Secret: "secret-182", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-183", Public: "public-183", Secret: "secret-183", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-184", Public: "public-184", Secret: "secret-184", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-185", Public: "public-185", Secret: "secret-185", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-186", Public: "public-186", Secret: "secret-186", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-187", Public: "public-187", Secret: "secret-187", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-188", Public: "public-188", Secret: "secret-188", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-189", Public: "public-189", Secret: "secret-189", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-190", Public: "public-190", Secret: "secret-190", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-191", Public: "public-191", Secret: "secret-191", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-192", Public: "public-192", Secret: "secret-192", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-193", Public: "public-193", Secret: "secret-193", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-194", Public: "public-194", Secret: "secret-194", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-195", Public: "public-195", Secret: "secret-195", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-196", Public: "public-196", Secret: "secret-196", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-197", Public: "public-197", Secret: "secret-197", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-198", Public: "public-198", Secret: "secret-198", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-199", Public: "public-199", Secret: "secret-199", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-200", Public: "public-200", Secret: "secret-200", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-201", Public: "public-201", Secret: "secret-201", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-202", Public: "public-202", Secret: "secret-202", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-203", Public: "public-203", Secret: "secret-203", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-204", Public: "public-204", Secret: "secret-204", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-205", Public: "public-205", Secret: "secret-205", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-206", Public: "public-206", Secret: "secret-206", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-207", Public: "public-207", Secret: "secret-207", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-208", Public: "public-208", Secret: "secret-208", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-209", Public: "public-209", Secret: "secret-209", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-210", Public: "public-210", Secret: "secret-210", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-211", Public: "public-211", Secret: "secret-211", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-212", Public: "public-212", Secret: "secret-212", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-213", Public: "public-213", Secret: "secret-213", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-214", Public: "public-214", Secret: "secret-214", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-215", Public: "public-215", Secret: "secret-215", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-216", Public: "public-216", Secret: "secret-216", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-217", Public: "public-217", Secret: "secret-217", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-218", Public: "public-218", Secret: "secret-218", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-219", Public: "public-219", Secret: "secret-219", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-220", Public: "public-220", Secret: "secret-220", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-221", Public: "public-221", Secret: "secret-221", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-222", Public: "public-222", Secret: "secret-222", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-223", Public: "public-223", Secret: "secret-223", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-224", Public: "public-224", Secret: "secret-224", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-225", Public: "public-225", Secret: "secret-225", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-226", Public: "public-226", Secret: "secret-226", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-227", Public: "public-227", Secret: "secret-227", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-228", Public: "public-228", Secret: "secret-228", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-229", Public: "public-229", Secret: "secret-229", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-230", Public: "public-230", Secret: "secret-230", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-231", Public: "public-231", Secret: "secret-231", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-232", Public: "public-232", Secret: "secret-232", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-233", Public: "public-233", Secret: "secret-233", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-234", Public: "public-234", Secret: "secret-234", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-235", Public: "public-235", Secret: "secret-235", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-236", Public: "public-236", Secret: "secret-236", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-237", Public: "public-237", Secret: "secret-237", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-238", Public: "public-238", Secret: "secret-238", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-239", Public: "public-239", Secret: "secret-239", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-240", Public: "public-240", Secret: "secret-240", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-241", Public: "public-241", Secret: "secret-241", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-242", Public: "public-242", Secret: "secret-242", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-243", Public: "public-243", Secret: "secret-243", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-244", Public: "public-244", Secret: "secret-244", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-245", Public: "public-245", Secret: "secret-245", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-246", Public: "public-246", Secret: "secret-246", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-247", Public: "public-247", Secret: "secret-247", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-248", Public: "public-248", Secret: "secret-248", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-249", Public: "public-249", Secret: "secret-249", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-250", Public: "public-250", Secret: "secret-250", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-251", Public: "public-251", Secret: "secret-251", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-252", Public: "public-252", Secret: "secret-252", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-253", Public: "public-253", Secret: "secret-253", Parameter: "parameter-1", Wrapped: ""},
	{Name: "fixture-254", Public: "public-254", Secret: "secret-254", Parameter: "parameter-2", Wrapped: ""},
	{Name: "fixture-255", Public: "public-255", Secret: "secret-255", Parameter: "parameter-3", Wrapped: ""},
	{Name: "fixture-256", Public: "public-256", Secret: "secret-256", Parameter: "parameter-4", Wrapped: ""},
	{Name: "fixture-257", Public: "public-257", Secret: "secret-257", Parameter: "parameter-5", Wrapped: ""},
	{Name: "fixture-258", Public: "public-258", Secret: "secret-258", Parameter: "parameter-6", Wrapped: ""},
	{Name: "fixture-259", Public: "public-259", Secret: "secret-259", Parameter: "parameter-0", Wrapped: ""},
	{Name: "fixture-260", Public: "public-260", Secret: "secret-260", Parameter: "parameter-1", Wrapped: ""},
}

func Fixtures() []Fixture { out := make([]Fixture, len(fixtures)); copy(out, fixtures); return out }
func FixtureByName(name string) (Fixture, bool) {
	for _, f := range fixtures {
		if f.Name == name {
			return f, true
		}
	}
	return Fixture{}, false
}
func BuildFixture(name, public, secret, parameter string) (Fixture, error) {
	w, e := WrapSecret(public, secret, parameter)
	return Fixture{Name: name, Public: public, Secret: secret, Parameter: parameter, Wrapped: w}, e
}
func VerifyFixture(f Fixture) bool {
	s, e := UnwrapSecret(f.Public, f.Wrapped, f.Parameter)
	return e == nil && s == f.Secret
}
